ghiscoding/aurelia-slickgrid

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts
This pull requests ensures that the `AureliaSlickgridCustomElement` will use the `dataset` when it is created without relying on `datasetChanged`
**Current State**
The `_dataset` is set in two methods: `attached` and `datasetChanged`. However, what happens if the view model is created and the dataset already has the data locally in a service, cache etc? That would mean that `datasetChanged` would never fire and the grid will always be empty. I experienced this problem when navigating back and forth between view-models. The first time I navigate to the view model, the grid is populated because I fetch the data from an API. However, when I navigate away and then back to that view model the grid becomes empty because `dataset` already has the data when the custom element is reattached to the …
=> fix(grid): init dataset on attached if it has data

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts
Use the Slick.EventHandler for subscriptions so we can use `unsubscribeAll`. I think with the original code we would have had to track each subscribed function and unsubscribe individually.
Also, as a precaution, add hasOwnProperty check on property enumeration
=> fix(events): unsubscribe from all events on detached

aurelia-slickgrid/src/aurelia-slickgrid/editors/index.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/multipleSelectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/singleSelectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/formatters/arrayToCsvFormatter.ts, aurelia-slickgrid/src/aurelia-slickgrid/formatters/collectionFormatter.ts, aurelia-slickgrid/src/aurelia-slickgrid/formatters/index.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/multipleSelectOption.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/global-utilities.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/utilities.ts, aurelia-slickgrid/src/aurelia-slickgrid/styles/slick-bootstrap.scss, aurelia-slickgrid/src/examples/slickgrid/example3.ts
This pull request brings two new editors and one small change and should close https://github.com/ghiscoding/aurelia-slickgrid/issues/18
**Purpose**
Select editors are very common with data to ensure data integrity and we already provide these are header filters.
**Features**
1. SelectListEditor - this editor uses most of the logic from the `SelectListFilter`. If the developer does not use `multiple-select` library, this editor falls back to a bootstrap `form-control`. For this to render property in the grid a new css rules was added.
2. MultipleSelectListEditor - this editor uses most of the logic from the `MultipleSelectListFilter`. If the developer does not use `multiple-select` library, this editor falls back to a bootstrap `form-control`
3. CollectionFormatter - the formatter will …
=> feat(selectEditors): add select grid editors

aurelia-slickgrid/src/aurelia-slickgrid/editors/singleSelectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/formatters/collectionFormatter.ts, aurelia-slickgrid/src/aurelia-slickgrid/formatters/index.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/global-utilities.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/utilities.ts, aurelia-slickgrid/src/examples/slickgrid/example3.ts
Having it on the Array.prototype causes issues with jquery extend and overall is risky. Also, and I am not sure how I missed this, but I was still using the `filter` property in the `collectionFormatter`. So i fixed that to make sure this new `findOrDefault` works.
closes #27
=> fix(utilities): move findOrDefault to a function

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/dateEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/multipleSelectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/singleSelectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/compoundDateFilter.ts
The current state supports editor dependencies through the Column.params property. By adding `Factory.of`, with aurelia's container, we are wrapping the creation of an editor in a function that already resolves injected dependencies at the time the grid is bound. `Factory.of` returns a function that passes any number of arguments to the editor. When Slickgrid calls `currentEditor = new useEditor({})`, the function created by `Factory.of` passes the slick grid arguments to the editor's constructor after the injected dependencies, so order matters.
```diff
-Passing i18n in the Grid Options for Formatter or Editors
+Passing i18n in the Grid Options for Formatter
```
Also I changed the `compoundDateFilter` file that was not using the injected `i18n` and using the older `params.i18n` logic. …
=> feat(editor): add dependency injection support in editors

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.html, aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts
@jmzagorski 
I would like like a review on this, grid height and width fix. I found this good [article](https://ilikekillnerds.com/2016/02/binding-with-style-in-aurelia/) on `css.bind` and I switched to that. I also found why I was resizing the grid at later point with `gridHeight` and `gridWidth`, it was because of the Pagination component that I use with Backend Service, it was taking 100% width of the screen instead of the grid size, unless I resized it. I found that if I put the width on the grid container, then set the grid to `width: 100%`, like it is shown in the [SlickGrid example](https://github.com/6pac/SlickGrid/blob/master/examples/example4-model.html#L37), that fixes my issue and the pagination still have a width 100%. 
So it all seems to work for me now, but I would really …
=> fix(grid): gridHeight & gridWidth not set, closes #35

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/gridEvent.service.ts, aurelia-slickgrid/src/examples/slickgrid/example3.html, aurelia-slickgrid/src/examples/slickgrid/example3.ts
This fixes a potential problem where the grid options as a parameter in the method are different than grid.getOptions. Users are allowed to change options after the grid is created by calling, for example, `grid.getOptions().showHeaderValue = false`. To make sure the options are up to date we need to call `grid.getOptions` when passing it as event args. 
Looking over `AureliaSlickgridCustomElement`, it should be fine to use `this.gridOptions` because most of the configuration is happening when the custom element is being created. The only potential issue I could see is if the `datasetChanged` fires after the grid is created. Then any call to `this.gridOptions` could potentially be out of data if the developer allows the user to change options later on. You can see this bug in example3 …
=> fix(eventService): use grid.getOptions for gridDefinition

aurelia-slickgrid/src/aurelia-slickgrid/editors/multipleSelectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/singleSelectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/multipleSelectFilter.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/singleSelectFilter.ts, aurelia-slickgrid/src/examples/slickgrid/example12.ts, aurelia-slickgrid/src/examples/slickgrid/example3.ts, aurelia-slickgrid/src/examples/slickgrid/example4.ts
`indexOf` must be used because `defaultValue` is an array for the `multipleSelectEditor`. the current `multipleSelectEditor` is broken and values are not loaded when the multiple select list is opened.
This reverts part of this [commit](https://github.com/ghiscoding/aurelia-slickgrid/commit/71916dc8bd80e257c310fa89485fc8a2e534a5d1) for the `multipleSelectEditor`.
The excel export and the sort still works with numbers. However, the current state of sorters will not sort "Task 2" and "Task 10" correctly regardless of the editors because those values are strings and not numbers. A separate issue would have to be opened to that. I updated `Example3.ts` to show that problem by allowing in Tasks greater than 10 in the prerequisite column.
If I can figure out/have permission to release a hot fix …
=> fix(editors): use indexOf in multiple select editor to load value

aurelia-slickgrid/src/aurelia-slickgrid/editors/floatEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/integerEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/styles/_variables.scss, aurelia-slickgrid/src/aurelia-slickgrid/styles/slick-default-theme.scss, aurelia-slickgrid/src/aurelia-slickgrid/styles/slick-editors.scss, aurelia-slickgrid/src/examples/slickgrid/example3.ts
- input should be of type number instead of text
- `onCellChange` should not trigger on `0` when input is really unchanged
- changed styling so that input are not transparent, however also add SASS variables in case user still want previous styling
@jmzagorski 
Just adding you as reviewer to make you inform of the PR since I know you use some Inline Editors
=> fix(editor): Int/Float Editors multiple small enhancements

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/controlAndPlugin.service.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/export.service.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/filter.service.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/graphql.service.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/grid-odata.service.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/gridExtra.service.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/gridState.service.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/groupingAndColspan.service.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/sort.service.ts, aurelia-slickgrid/src/examples/slickgrid/example10.html, aurelia-slickgrid/src/examples/slickgrid/example8.ts, client-cli/src/examples/slickgrid/example8.js, doc/github-demo/src/examples/slickgrid/example8.ts
- removed all references from all init/attach Services
**Note** it does not include the refactoring of `gridEventService.attachOnCellChange` and `gridEventService.attachOnClick` since that was already done in a separate PR #51 
@jmzagorski 
It's a long time that I wanted to cleanup these arguments and only use `grid` and `dataView` objects. We can get `options` and `columnDefinitions` from the `grid` and so we should do that everywhere.
I tested all the grids with all features and everything seems to work as usual.
Hopefully this will help in issue #36 (multiple grids in one view)
Note, this PR has to be merged **only after** PR #51 , hopefully without conflicts afterward but it's possible and will address at that time if that happens.
=> refactor(services): remove gridOptions and columnDefinitions

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts
`this.dataview.setItems`  will remove any sorts that were on the grid. I found this when `datasetChanged` was called and refreshed the grid. You can duplicate this bug in example3 as such:
```
dataviewChanged(dataview) {
this.dataview = dataview;
const data = [ ...this.dataview.getItems() ]
// you have 6 seconds to sort the grid and then watch it go back to the original
setTimeout(() => this.dataset = data, 6000);
}
```
=> fix(dataview): preserve any previous sort when resetting items

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/resizer.service.ts
- if user pass any of the two, even when the grid option enableAutoResize is enabled, grid will be resized only on the argument not provided and not override provided one.
- Example, let say the user passes `gridHeight="300"` to the View, the `autoResize` Service will only resize the width and never the height because it is now a fixed height.
=> feature(resize): use gridHeight or gridWidth when provided on autoResize

aurelia-slickgrid/src/aurelia-slickgrid/models/collectionFilterBy.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/collection.service.ts, aurelia-slickgrid/src/examples/slickgrid/example3.ts, client-cli/src/examples/slickgrid/example3.js, doc/github-demo/src/examples/slickgrid/example3.ts
The default operator 'EQ' was switched to filter for the value instead of excluding it. Also, an explicit check for `undefined` in the `collectionFilterBy.value` was added in case the value is actual false, 0, blank or null.
New operator type filters:
1.  `in`: supports `collectionFilterBy.property` as a nested array, and if the `collectionFilterBy.value` exists in the nested array, the parent item will NOT be filtered. For example: `collection: [{ foo: ['bar'] }, { foo: ['foo'] }]`, `collectionFilterBy.property: 'foo'`, `collectionFilterBy.value: 'bar'` will return the first item in the collection only
2. `notIn`: oppostie of `in`
3. `contains`: assumes the `collectionFilterBy.value` is an array and will check if any of those values exists in the `collectionFilterBy.property`. For …
=> feat(filters): add more operator types to collection svc filter

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/controlAndPlugin.service.ts, aurelia-slickgrid/src/examples/slickgrid/example12.html, aurelia-slickgrid/src/examples/slickgrid/example12.ts, client-cli/src/examples/slickgrid/example12.html, client-cli/src/examples/slickgrid/example12.js, doc/github-demo/src/examples/slickgrid/example12.html, doc/github-demo/src/examples/slickgrid/example12.ts
- We can dynamically add or change column definitions, see Example12 for a demo
- reference to issue #57
=> feature(grid): ability to dynamically add or change Column Headers

aurelia-slickgrid/src/aurelia-slickgrid/filter-conditions/dateFilterCondition.ts, aurelia-slickgrid/src/aurelia-slickgrid/filter-conditions/dateIsoFilterCondition.ts, aurelia-slickgrid/src/aurelia-slickgrid/filter-conditions/dateUsFilterCondition.ts, aurelia-slickgrid/src/aurelia-slickgrid/filter-conditions/dateUsShortFilterCondition.ts, aurelia-slickgrid/src/aurelia-slickgrid/filter-conditions/dateUtcFilterCondition.ts, aurelia-slickgrid/src/examples/slickgrid/example4.ts
Returning true on an invalid date will keep it on the grid when it should be filtered out.
associates #68
will be closed when sorting is fixed in a separate PR
=> fix(filters): return false when invalid date

aurelia-slickgrid/src/aurelia-slickgrid/sorters/dateIsoSorter.ts, aurelia-slickgrid/src/aurelia-slickgrid/sorters/dateSorter.ts, aurelia-slickgrid/src/aurelia-slickgrid/sorters/dateUsShortSorter.ts, aurelia-slickgrid/src/aurelia-slickgrid/sorters/dateUsSorter.ts, aurelia-slickgrid/src/aurelia-slickgrid/sorters/sorterUtilities.ts, aurelia-slickgrid/src/examples/slickgrid/example4.ts
Returning zero every time value1 or value 2 is invalid will result in an incorrect sort because it would not sort one value higher than the other (e.g if value1 was 2018-05-24 and value2 was null, these would be sorted as equals). We want invalid dates to be grouped together in the sort and this accomplishes that.
We could add additional logic such that if both were invalid that we return 0, but this commit does the job just fine. Since the logic was the same for every sorter, with the exception of format and strict, I created a utility function that took all the parameters
closes #68
associates to PR #69
=> fix(sorters): return -1 or 1 for invalid dates

aurelia-slickgrid/src/aurelia-slickgrid/models/gridOption.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/controlAndPlugin.service.ts, aurelia-slickgrid/src/examples/slickgrid/example10.ts, aurelia-slickgrid/src/examples/slickgrid/example3.ts
This PR brings 2 in 1 features
- Add a way to Preselect Row Selection through Grid Options
- Expose and Dispose of all Controls/Plugins through an array for easier logic
- also add a Getter for all or by name
=> feat(rowSelect): add preselectedRows and expose all Plugin

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/sort.service.ts
- fixes Presets unintended behavior after Clearing Sorting, then Clearing Filters. 
- also refactored dispatch of Custom Event to be 1 liner for cleaner code
@jmzagorski 
Thanks a lot in finding this one, I was pulling my hair.
The DataView subscribe was way overkill to do the presets, just calling the `loadLocalPresets` after the DataView finished updating is more than enough. That is much cleaner and it works all the time (one time that is... lol)
=> fix(sort): Presets & Sort caused unintended behavior w/dataview changed

aurelia-slickgrid/src/aurelia-slickgrid/filters/compoundSliderFilter.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/index.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/inputRangeFilter.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/sliderFilter.ts, aurelia-slickgrid/src/aurelia-slickgrid/index.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/columnFilter.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/filterCallback.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/styles/_variables.scss, aurelia-slickgrid/src/aurelia-slickgrid/styles/slick-plugins.scss, aurelia-slickgrid/src/examples/slickgrid/example12.ts, aurelia-slickgrid/src/examples/slickgrid/example15.ts, aurelia-slickgrid/src/examples/slickgrid/example9.ts
Use an input range to add what looks like a slider filter. 
- when the slider is set to 0 (default value), it returns all values
- when going over over, it will return only the rows with selected value
- styled to be cross-browser compatible
- tooltip only shown in IE, I wish we could add them for all browser though
@jmzagorski 
It's not yet finished but it's functional, so don't approve yet. I just need to clear up the styling and see if we can add tooltip for all browser. Not as useful without tooltip of the value
=> feat(filter): add new slider filter (input range)

aurelia-slickgrid/src/aurelia-slickgrid/editors/longTextEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/selectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/selectFilter.ts
- Single/Multiple Editors now closes the drop when tabbing away (blur)
- also fixed the `focus()` function inside the Editor
- demo shown below, I used tab key and arrows to test it out
- Since this seems to work quite good, I should probably do the same on the Select Filter as well. I'll add another commit within same PR
=> fix(editor): Select Editor should close when tabbing away, fixes #92

aurelia-slickgrid/src/aurelia-slickgrid/editors/selectEditor.ts, aurelia-slickgrid/src/examples/slickgrid/example3.ts, doc/github-demo/src/examples/slickgrid/example3.ts
- the prerequisites property should only be filled with integer values and to get the missing "Task" text, inside the Editor we use a `customStructure` with Prefix, but we also need to use a Formatter to display it in the grid
- also the `selectEditor.ts` did not change, however some code cleaning was done in it
@jmzagorski 
So the issue #95 was all in the demo itself, nothing to do with the SelectEditor (I did some code cleanup but the functionality is exactly the same). So the reason was explained a bit inside the commit (on the top), but basically since I wanted to demo the use of `customStructure` inside an Editor with Prefix, I should make sure to use the prerequisites as an array of integers (without the word "Task"). But then, I'm missing the word text since they are only integers, …
=> fix(example): prerequisite prop should only use integer values, closes #95

aurelia-slickgrid/src/aurelia-slickgrid/services/export.service.ts
This was reported in the `Angular-Slickgrid` repo under this [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/67)
=> fix(export): Export should work with datasetIdPropertyName defined

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/selectFilter.ts
This PR removes the `aurelia-http-client` dependencies. I tested and fixed both Filters & Editors (the latter is in `aurelia-slickgrid.ts`). 
I had to move the `Promise` check as the first check since incorrectly was getting caught by the other checks, after doing so it was all good. I tested with `console.log` on all 3 (Filter & Editor) and switch from `aurelia-http-client`, to `aurelia-fetch-client` to `Promise`.
=> fix(http): remove aurelia-http-client dependency, closes #101

aurelia-slickgrid/src/aurelia-slickgrid/services/sort.service.ts
This PR is a continuation of PR #100 and is to Sort Complex Objects
For example, let say that we have this dataset
```typescript
const dataset = [
{ item: 'HP Desktop', buyer: { id: 1234, address: { street: '123 belleville', zip: 123456 }},
{ item: 'Lenovo Mouse', buyer: { id: 456, address: { street: '456 hollywood blvd', zip: 789123 }}
];
```
We can now filter the zip code from the buyer's address using this filter:
```typescript
this.columnDefinitions = [
{
// the zip is a property of a complex object which is under the "buyer" property
// it will use the "field" property to explode (from "." notation) and find the child value
id: 'zip', name: 'ZIP', field: 'buyer.address.zip', sortable: true
// id: 'street',  ...
];
```
=> feat(sort): add posibility to sort complex objects

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.html, aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/checkboxEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/dateEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/longTextEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/selectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/sliderEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/gridOption.interface.ts, aurelia-slickgrid/src/examples/slickgrid/example3.html, aurelia-slickgrid/src/examples/slickgrid/example3.ts
The auto commit flag will attempt to commit the current editor when the
editor is focused out. However, not all editors behave the same so extra
logic had to be included in some editors. This means that the grid may not
be able to auto commit custom editors and it will be the
responsibility of the user building the editor.
**checkboxEditor**: Can be handled by the focusout event, but a click event
was added in the editor to make it behave more like a checkbox
**dateEditor**, **sliderEditor**: Prevent focus to the next editor
**longTextEditor**: Add focusout event to textarea, grid does not capture event
**selectEditor**: No focusout event so commit on close
**others**: handled by aurelia-slickgrid subscription to focusout
Also, i tried to build the code and it is broken right now from …
=> feat(editor): Add auto commit edit flag to grid options

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/global-grid-options.ts
- user should be able to have `enableFiltering: true` and still hide the filter row on page load with `showHeaderRow: false`, doing this would still create all filters but it will also hide the filter row after page load, it's important to hide it AFTER, else the filters won't be created at all.
=> fix(header): use showHeaderRow flag correctly when defined by user

aurelia-slickgrid/assets/lib/multiple-select/multiple-select.js, aurelia-slickgrid/src/aurelia-slickgrid/editors/selectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/selectFilter.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/collectionCustomStructure.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/multipleSelectOption.interface.ts, aurelia-slickgrid/src/examples/slickgrid/example4.ts
- in some cases the selected text might be too wide to show as selected text (on `<select>` element), this PR adds possibility to use a different property (of your collection objects) to display shorter text
```typescript
{ 
id: 'duration', name: 'Duration (days)', field: 'duration', 
filter: {
collectionAsync: this.http.get<{ option: string; value: string; }[]>(URL_SAMPLE_COLLECTION_DATA),
customStructure: {
value: 'value',
label: 'label',
optionLabel: 'value', // if selected text is too long, we can use option labels instead
labelSuffix: 'text',
},
model: Filters.multipleSelect,
// we could add certain option(s) to the "multiple-select" plugin
filterOptions: {
// if we want to display shorter text as the selected text (on the select filter itself, parent element)
useSelectOptionLabel: …
```
=> feat(select): add option to use label as selected text

aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/grid.service.ts, aurelia-slickgrid/src/examples/slickgrid/example17.html, aurelia-slickgrid/src/examples/slickgrid/example17.ts, aurelia-slickgrid/src/examples/slickgrid/index.ts, doc/github-demo/package.json, doc/github-demo/src/examples/slickgrid/example17.html, doc/github-demo/src/examples/slickgrid/example17.ts, doc/github-demo/src/examples/slickgrid/index.ts
- this provide access for user to use their own dataview
- the lib uses dataview in it's core, so user will have to re-implement a lot of these features, like file/sort/...
This PR is the implementation of this SlickGrid [AJAX Example](http://6pac.github.io/SlickGrid/examples/example6-ajax-loading.html) with Remote Model
=> feat(remote): add Remote Model example with custom dataview

aurelia-slickgrid/src/aurelia-slickgrid/extensions/headerMenuExtension.ts, aurelia-slickgrid/src/aurelia-slickgrid/global-grid-options.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/gridMenuItem.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/headerMenu.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/headerMenuItem.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/styles/_variables.scss, aurelia-slickgrid/src/aurelia-slickgrid/styles/slick-controls.scss, aurelia-slickgrid/src/aurelia-slickgrid/styles/slick-plugins.scss, aurelia-slickgrid/src/examples/slickgrid/example8.ts, aurelia-slickgrid/src/examples/slickgrid/example9.ts, doc/github-demo/src/examples/slickgrid/example8.ts, doc/github-demo/src/examples/slickgrid/example9.ts
This PR requires the [SlickGrid PR #319](https://github.com/6pac/SlickGrid/pull/319) to be merged for this to work.
=> feat(divider): add divider option to Grid Menu & Column Header Menu

aurelia-slickgrid/package.json, aurelia-slickgrid/src/aurelia-slickgrid/extensions/cellExternalCopyManagerExtension.ts, aurelia-slickgrid/src/aurelia-slickgrid/formatters/decimalFormatter.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/formatter.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/formatterResultObject.interface.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/index.ts, aurelia-slickgrid/src/aurelia-slickgrid/services/export.service.ts, aurelia-slickgrid/src/examples/slickgrid/example2.ts, aurelia-slickgrid/src/styles.css, doc/github-demo/src/examples/slickgrid/example2.ts, doc/github-demo/src/styles/styles.css, package.json
- using the object return format, you can add css classes directly to the cell instead of having to create separate `<div>`
- since PR in SlickGrid core lib got merged it now accepts tooltip:: 6pac/SlickGrid#330
- also addClasses & removeClasses should be optional types
=> refactor(formatter): Formatter can also return objects

aurelia-slickgrid/assets/lib/multiple-select/multiple-select.js, aurelia-slickgrid/src/aurelia-slickgrid/editors/autoCompleteEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/floatEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/integerEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/longTextEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/sliderEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/textEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/compoundSliderFilter.ts, aurelia-slickgrid/src/examples/slickgrid/custom-inputEditor.ts, doc/github-demo/src/examples/slickgrid/custom-inputEditor.ts
- to remove any weird behaviors but also for gabage collection
- the multiple-select.js was causing some weird behavior, if user would go on the GraphQL example, then choose a different company in the multiple select filter and click away (not on OK button) to simulate a blur, the spinner would never show up. The reason was because there was a click event bound to the document and was never unbound
=> fix(filter): all jquery .on bound event should also be unbound

aurelia-slickgrid/src/aurelia-slickgrid/editors/selectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/filters/selectFilter.ts, aurelia-slickgrid/src/examples/slickgrid/example6.ts, doc/github-demo/src/examples/slickgrid/example6.ts
- since the `.ms-drop` element is pushed to the body (container) because of some SlickGrid limitation. So because it exist in the html body, we need to remove the drop in a separate jquery remove call
=> fix(filter): select filter drop doesn't get removed on destroy

aurelia-slickgrid/src/aurelia-slickgrid/constants.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/autoCompleteEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/checkboxEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/dateEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/floatEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/integerEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/longTextEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/selectEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/sliderEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/editors/textEditor.ts, aurelia-slickgrid/src/aurelia-slickgrid/models/columnEditor.interface.ts, aurelia-slickgrid/src/examples/slickgrid/custom-inputEditor.ts, doc/github-demo/src/examples/slickgrid/custom-inputEditor.ts
- these 2 new options might not be supported by all Editors (e.g. checkbox doesn't use ENTER key)
- the "alwaysSaveOnEnterKey" can be helpful if user want to save value regardless if it's null or not
- also fixed integer editor validation, a few validations were missing like minValue/maxValue/...
=> feat(editors): add "required" and "alwaysSaveOnEnterKey" options

src/aurelia-slickgrid/models/checkboxSelector.interface.ts, src/examples/slickgrid/example10.ts
- for example, if user want to display/use row selection (checkbox) icons only on every 2nd row, we can override this logic
=> feat(rowSelection): user can override row selection checkbox logic

src/aurelia-slickgrid/models/column.interface.ts, src/aurelia-slickgrid/services/__tests__/graphql.service.spec.ts, src/aurelia-slickgrid/services/filter.service.ts, src/aurelia-slickgrid/services/graphql.service.ts, src/aurelia-slickgrid/services/grid-odata.service.ts, src/aurelia-slickgrid/services/sort.service.ts
- both "queryFieldFilter" and "queryFieldSorter" should have precedence over "queryField", then "field". For example (1- "queryFieldFilter", if not found then 2- "queryField", if not found then "field"
=> fix(queryField): queryFieldFilter and queryFieldSorter have precedence

src/aurelia-slickgrid/extensions/__tests__/autoTooltipExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/cellExternalCopyManagerExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/checkboxSelectorExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/columnPickerExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/draggableGroupingExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/groupItemMetaProviderExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/headerButtonExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/rowDetailViewExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/rowMoveManagerExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/rowSelectionExtension.spec.ts, src/aurelia-slickgrid/extensions/autoTooltipExtension.ts, src/aurelia-slickgrid/extensions/cellExternalCopyManagerExtension.ts, src/aurelia-slickgrid/extensions/checkboxSelectorExtension.ts, src/aurelia-slickgrid/extensions/columnPickerExtension.ts, src/aurelia-slickgrid/extensions/draggableGroupingExtension.ts, src/aurelia-slickgrid/extensions/gridMenuExtension.ts, src/aurelia-slickgrid/extensions/groupItemMetaProviderExtension.ts, src/aurelia-slickgrid/extensions/headerButtonExtension.ts, src/aurelia-slickgrid/extensions/headerMenuExtension.ts, src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts, src/aurelia-slickgrid/extensions/rowMoveManagerExtension.ts, src/aurelia-slickgrid/extensions/rowSelectionExtension.ts, src/aurelia-slickgrid/models/extension.interface.ts, src/aurelia-slickgrid/services/__tests__/extension.service.spec.ts, src/aurelia-slickgrid/services/extension.service.ts
- add a new "getAddonInstance" method to all extension
- this new method returns the addon instance which is typically the same as the one returned from the register() method, but can be called at any time
=> fix(gridMenu): external grid menu was not triggering

cypress/integration/example1.spec.js, cypress/integration/example6.spec.js, cypress/integration/home.spec.js, src/aurelia-slickgrid/services/__tests__/filter.service.spec.ts, src/aurelia-slickgrid/services/filter.service.ts, test/tsconfig.spec.json
- when trying to clear a filter that was empty, there is no reason to trigger a filter change
- to replicate the issue, you could go to the OData or GraphQL example and hover over a column with an empty filter, then choose "Clear Filter" from the header menu. The spinner should stop
=> fix(backend): clear empty filter by header menu not stopping spinner

cypress/integration/example10.spec.js, src/aurelia-slickgrid/services/__tests__/extension.service.spec.ts, src/aurelia-slickgrid/services/extension.service.ts, src/examples/slickgrid/example10.html, src/examples/slickgrid/example10.ts
- this was a regression bug, cannot pinpoint exactly since when this regression bug started
- the isssue, row selection and filtering are completely independent, they don't talk to each other and the filtering as no clue which row it was selected prior to the filter, so the best we can do is to remove any row selection after typing a search filter (filtering)
- update Jest unit tests & add Cypress E2E tests to cover this in the UI as well
=> fix(selection): selected row should be none after filtering

src/aurelia-slickgrid/aurelia-slickgrid.ts, src/aurelia-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/columnPickerExtension.ts, src/aurelia-slickgrid/extensions/gridMenuExtension.ts, src/aurelia-slickgrid/extensions/headerMenuExtension.ts, src/aurelia-slickgrid/services/__tests__/extension.service.spec.ts, src/aurelia-slickgrid/services/__tests__/gridState.service.spec.ts, src/aurelia-slickgrid/services/__tests__/sort.service.spec.ts, src/aurelia-slickgrid/services/extension.service.ts, src/aurelia-slickgrid/services/gridState.service.ts, src/aurelia-slickgrid/services/sort.service.ts, src/examples/slickgrid/example15.html, src/examples/slickgrid/example15.ts, test/cypress/integration/example15.spec.js, test/cypress/integration/example9.spec.js, test/cypress/package.json, test/cypress/support/commands.js, test/cypress/tsconfig.json
- there was mainly 3 problems
1. ColumnPicker & GridMenu were re-registered but their instances were not overwritten and because of that, the onColumnsChanged in the GridState was never triggering anymore because the subscribe was on the instance that no longer existed
2. we were using the setColumns with allColumns, that was a regression introduced by previous commit, this in terms was cancelling any presets of columns from coming in
3. header menu was not triggering any changes, hiding a column and/or sorting a column had no effect on the Grid State.
- Example 15 is the reference for Grid State & Presets
=> fix(presets): Grid State & Presets stopped working for columns

src/aurelia-slickgrid/models/odataOption.interface.ts, src/aurelia-slickgrid/services/__tests__/grid-odata.service.spec.ts, src/aurelia-slickgrid/services/grid-odata.service.ts, src/examples/slickgrid/example3.html, src/examples/slickgrid/example5.html, src/examples/slickgrid/example5.ts, test/cypress/integration/example5.spec.js
- defaults to OData version 2 (which uses substringof)
- ref #88 and Angular-Slickgrid issue [#263](https://github.com/ghiscoding/Angular-Slickgrid/issues/263)
- Tasks
`$top=20&$orderby=Name asc&$filter=(Gender eq 'male' and substringof('John', Name))`
`$top=20&$orderby=Name asc&$filter=(contains(Name, 'John') and Gender eq 'male')`
=> fix(odata): use contains with OData version 4, closes #88 

src/aurelia-slickgrid/aurelia-slickgrid.html, src/aurelia-slickgrid/aurelia-slickgrid.ts, src/aurelia-slickgrid/editors/longTextEditor.ts, src/aurelia-slickgrid/extensions/extensionUtility.ts, src/aurelia-slickgrid/extensions/gridMenuExtension.ts, src/aurelia-slickgrid/extensions/headerMenuExtension.ts, src/aurelia-slickgrid/filters/compoundInputFilter.ts, src/aurelia-slickgrid/filters/selectFilter.ts, src/aurelia-slickgrid/models/aureliaGridInstance.interface.ts, src/aurelia-slickgrid/models/index.ts, src/aurelia-slickgrid/models/pager.interface.ts, src/aurelia-slickgrid/models/pagination.interface.ts, src/aurelia-slickgrid/services/__tests__/backend-utilities.spec.ts, src/aurelia-slickgrid/services/__tests__/pagination.service.spec.ts, src/aurelia-slickgrid/services/backend-utilities.ts, src/aurelia-slickgrid/services/export.service.ts, src/aurelia-slickgrid/services/filter.service.ts, src/aurelia-slickgrid/services/graphql.service.ts, src/aurelia-slickgrid/services/grid.service.ts, src/aurelia-slickgrid/services/index.ts, src/aurelia-slickgrid/services/pagination.service.ts, src/aurelia-slickgrid/services/sort.service.ts, src/aurelia-slickgrid/slick-pagination.html, src/aurelia-slickgrid/slick-pagination.ts, src/examples/slickgrid/example5.html, src/examples/slickgrid/example5.ts, src/examples/slickgrid/example6.html, src/examples/slickgrid/example6.ts
- with this new Service, user can now programmatically change page from its application since the Pagination Service is now exposed to the outside
- manually adding items (via the grid service addItem()) shouldn't reset pagination to page 1
- completely change how we pass the options to the child pagination component
- no longer relying on the entire grid option to be passed to the pagination (which was error pron)
- now passes only the essential options required by the pagination
=> feat(backend): extract Pagination into its own Service to expose methods

src/aurelia-slickgrid/services/__tests__/grid.service.spec.ts, src/aurelia-slickgrid/services/grid.service.ts
ref `Angular-Slickgrid` [ref #308](https://github.com/ghiscoding/Angular-Slickgrid/pull/308)
=> fix(gridService): addItem/updatedItemById pass array to setSelectedRows

src/aurelia-slickgrid/editors/__tests__/selectEditor.spec.ts, src/aurelia-slickgrid/editors/selectEditor.ts, src/aurelia-slickgrid/models/columnEditor.interface.ts
- when editing a cell with a complex object dot notation, say "user.firstName" and our collection is option/label pair for the user not for their first name, we can use the new property of complexObjectPath: 'user' to tell the editable object to use the "user" and not "user.firstName" when selecting from dropdown
=> fix(editor): provide complex object override path for select editor

src/aurelia-slickgrid/editors/__tests__/dateEditor.spec.ts, src/aurelia-slickgrid/editors/__tests__/sliderEditor.spec.ts, src/aurelia-slickgrid/editors/dateEditor.ts, src/aurelia-slickgrid/editors/sliderEditor.ts
- certain Editors were triggering a save when clicking/opening the Editor when autocommit was enabled even though the value if the field was the same since we just opened the editor.
=> fix(editor): autocommit should not save if value is the same as before

src/aurelia-slickgrid/editors/selectEditor.ts, src/aurelia-slickgrid/models/columnEditor.interface.ts, src/examples/slickgrid/example23.ts
- deprecate `elementOptions` and push to use `editorOptions` instead
=> fix(editor): use editorOptions only 

src/aurelia-slickgrid/filters/compoundInputFilter.ts, src/aurelia-slickgrid/formatters/checkmarkFormatter.ts, src/aurelia-slickgrid/services/__tests__/pagination.service.spec.ts, src/aurelia-slickgrid/services/pagination.service.ts, src/aurelia-slickgrid/slick-pagination-without-i18n.spec.ts, src/aurelia-slickgrid/slick-pagination.html, src/aurelia-slickgrid/slick-pagination.spec.ts, src/aurelia-slickgrid/styles/_variables.scss, src/aurelia-slickgrid/styles/slick-plugins.scss, test/cypress/integration/example15.spec.js, test/cypress/integration/example5.spec.js, test/cypress/package.json
- if we filter the data and an empty dataset is returned, we should display "Page 1 of 1", not "Page 0 of 0". Also instead of "0-0 of 0 items", we should hide the "0-0" and only display "0 items". This matches roughly what UI-Grid does (in their case, they actually even hide the total count).
- this fixes some small issues that I have seen, sometime the page 0 of 0 was sticking even though we removed the filter, so it's better to use Page 1 of 1 as a minimum
- update Cypress E2E test
**BEFORE**
**AFTER**
=> fix(pagination): never display page 0, minimum should be page 1

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/services/__tests__/filter.service.spec.ts, src/aurelia-slickgrid/services/__tests__/sort.service.spec.ts, src/aurelia-slickgrid/services/filter.service.ts, src/aurelia-slickgrid/services/sort.service.ts, src/examples/slickgrid/example18.html, src/examples/slickgrid/example18.ts, src/examples/slickgrid/example23.html, src/examples/slickgrid/example23.ts, src/examples/slickgrid/example4.html, src/examples/slickgrid/example4.ts, src/examples/slickgrid/example5.html, src/examples/slickgrid/example5.ts, src/examples/slickgrid/example6.html, src/examples/slickgrid/example6.ts, test/cypress/integration/example23.spec.js, test/cypress/integration/example4.spec.js, test/cypress/integration/example5.spec.js, test/cypress/integration/example6.spec.js
- prior to this change, we could update Sorting (sorters) only through "presets" the caviat was that it was only on first page load. Now with this new change we will be to update Sorting on the fly at any time.
=> feat(sorting): provide method to apply grid sorting dynamically

src/aurelia-slickgrid/services/__tests__/filter.service.spec.ts, src/aurelia-slickgrid/services/__tests__/sort.service.spec.ts, src/aurelia-slickgrid/services/filter.service.ts, src/aurelia-slickgrid/services/sort.service.ts
- allow to bypass changed events when calling updateFilters / updateSorting
- also allow to bypass calling the backend query (
- useful when calling both updates in sequence and we want only 1 query sent
=> feat(events): allow to bypass changed events when calling updateFilters/Sorting

src/aurelia-slickgrid/editors/__tests__/autoCompleteEditor.spec.ts, src/aurelia-slickgrid/filters/__tests__/compoundDateFilter.spec.ts, src/aurelia-slickgrid/filters/__tests__/dateRangeFilter.spec.ts, src/aurelia-slickgrid/filters/compoundDateFilter.ts, src/aurelia-slickgrid/filters/dateRangeFilter.ts, src/aurelia-slickgrid/formatters/__tests__/decimalFormatter.spec.ts, src/aurelia-slickgrid/services/__tests__/filter.service.spec.ts, src/aurelia-slickgrid/services/__tests__/grid.service.spec.ts, src/aurelia-slickgrid/services/grid.service.ts
- ref Angular-Slickgrid issue [#346](https://github.com/ghiscoding/Angular-Slickgrid/issues/346)
- when using a locale that Flatpickr doesn't support, like "ua", it should use "en" (English) as default locale.
- it will display a console warning that this locale is not supported but not throw an error (unless user set a different locale, see next)
- user can choose to override the locale by setting locale to use via 
- `filter: { filterOptions: { locale: 'en' } }`
New behavior with this PR, it will now show a console warning to advise user that the locale is not supported, it will use English locale instead of throwing an error
=> fix(filter): Date Filters using Flatpickr throw error w/invalid locale

src/aurelia-slickgrid/services/__tests__/filter.service.spec.ts, src/aurelia-slickgrid/services/filter.service.ts, src/examples/slickgrid/example13.ts, src/examples/slickgrid/example18.ts
- when calling grouping and sort, user must manually update the sort icons
- the sort icons are not inter-connected to the sorting itself, they must be set separately, exposing a quick method in the filter service to deal with that
=> fix(sort): add sort icons to grouping examples

src/aurelia-slickgrid/services/__tests__/graphql.service.spec.ts, src/aurelia-slickgrid/services/graphql.service.ts, src/examples/slickgrid/example23.ts
- for example a GraphQL query like this 
- `query{ users(first:20, offset:40){ totalCount, nodes{ id, field1, field2 }}}` 
- without pagination should simply be
- `query{ users{ id, field1, field2 }}`
=> fix(graphql): disable pagination should remove any page info from query

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/extensions/__tests__/cellMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/columnPickerExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/contextMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/columnPickerExtension.ts, src/aurelia-slickgrid/extensions/gridMenuExtension.ts, src/aurelia-slickgrid/models/column.interface.ts, src/aurelia-slickgrid/services/__tests__/excelExport.service.spec.ts, src/aurelia-slickgrid/services/__tests__/export.service.spec.ts, src/aurelia-slickgrid/services/__tests__/extension.service.spec.ts, src/aurelia-slickgrid/services/excelExport.service.ts, src/aurelia-slickgrid/services/export.service.ts, src/aurelia-slickgrid/services/extension.service.ts, src/examples/slickgrid/example12.ts, src/examples/slickgrid/example15.ts, src/examples/slickgrid/example23.ts, src/examples/slickgrid/example24.ts, src/examples/slickgrid/example25.ts, src/examples/slickgrid/example3.ts, src/examples/slickgrid/example6.ts, src/examples/slickgrid/example8.ts, src/examples/slickgrid/example9.ts
- deprecate "headerKey" in the future and use "nameKey" instead which aligns with the "name" property in the column definitions
=> break(column): change "headerKey" to "nameKey" to align with column name

src/aurelia-slickgrid/constants.ts, src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts, src/aurelia-slickgrid/custom-elements/__tests__/slick-pagination-without-i18n.spec.ts, src/aurelia-slickgrid/custom-elements/__tests__/slick-pagination.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/custom-elements/slick-pagination.ts, src/aurelia-slickgrid/custom-elements/slickgridEventAggregator.ts, src/aurelia-slickgrid/extensions/headerMenuExtension.ts, src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts, src/aurelia-slickgrid/services/__tests__/excelExport.service.spec.ts, src/aurelia-slickgrid/services/__tests__/export.service.spec.ts, src/aurelia-slickgrid/services/__tests__/grid.service.spec.ts, src/aurelia-slickgrid/services/__tests__/groupingAndColspan.service.spec.ts, src/aurelia-slickgrid/services/__tests__/pagination.service.spec.ts, src/aurelia-slickgrid/services/__tests__/resizer.service.spec.ts, src/aurelia-slickgrid/services/excelExport.service.ts, src/aurelia-slickgrid/services/export.service.ts, src/aurelia-slickgrid/services/filter.service.ts, src/aurelia-slickgrid/services/grid-odata.service.ts, src/aurelia-slickgrid/services/grid.service.ts, src/aurelia-slickgrid/services/gridState.service.ts, src/aurelia-slickgrid/services/groupingAndColspan.service.ts, src/aurelia-slickgrid/services/pagination.service.ts, src/aurelia-slickgrid/services/resizer.service.ts, src/aurelia-slickgrid/services/sort.service.ts, src/examples/slickgrid/example13.html, src/examples/slickgrid/example13.ts, src/examples/slickgrid/example6.ts
- we now have 2 instances a Event Aggregator, 1x is Global (mostly for I18N) and another 1x is for the plugin itself (events that are sent only internally and in a transient mode)
=> (pagination): fix singleton issues found in Pagination and elsewhere

package.json, src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/global-grid-options.ts, src/aurelia-slickgrid/models/currentColumn.interface.ts, src/aurelia-slickgrid/models/currentRowSelection.interface.ts, src/aurelia-slickgrid/models/gridState.interface.ts, src/aurelia-slickgrid/models/gridStateChange.interface.ts, src/aurelia-slickgrid/models/gridStateType.enum.ts, src/aurelia-slickgrid/models/index.ts, src/aurelia-slickgrid/services/__tests__/grid.service.spec.ts, src/aurelia-slickgrid/services/__tests__/gridState.service.spec.ts, src/aurelia-slickgrid/services/__tests__/pagination.service.spec.ts, src/aurelia-slickgrid/services/grid.service.ts, src/aurelia-slickgrid/services/gridState.service.ts, src/aurelia-slickgrid/services/pagination.service.ts, src/examples/slickgrid/example10.html, src/examples/slickgrid/example10.ts, test/cypress/cypress.json, test/cypress/integration/example10.spec.js, test/cypress/integration/example15.spec.js
- with the "syncGridSelection" enabled in the DataView we can now add the Row Selection to the Grid State & Presets (for that the flags "enableCheckboxSelector" or "enableRowSelection" must be enabled)
- the information of the Selected Rows when using Pagination is not available in SlickGrid, it only returns current page selection, so for that we have to implement it ourselve
=> feat(selection): preserve row selection & add it to Grid State & Presets

src/aurelia-slickgrid/services/__tests__/pagination.service.spec.ts, src/aurelia-slickgrid/services/pagination.service.ts
- when using local grid, the DataView should be reset to page 0
=> fix(pagination): on filter change pagination should reset to 1st page

src/aurelia-slickgrid/models/column.interface.ts, src/aurelia-slickgrid/models/excelExportOption.interface.ts, src/aurelia-slickgrid/services/__tests__/excelExport.service.spec.ts, src/aurelia-slickgrid/services/excelExport.service.ts, src/examples/slickgrid/example24.ts
code referenced from another fork in this particular [commit](https://github.com/drinac/Angular-Slickgrid/commit/275e099c8a55f0eb43935249dbf71e0c02066afe) 
- add the following `excelExportOptions`
- `customColumnWidth` 
- `columnHeaderStyle`
- add the following Column options
- `exportColumnWidth`
- `exportCustomGroupTotalsFormatter`
=> feat(excel): add some extra styling & width options for Excel export

src/aurelia-slickgrid/services/__tests__/resizer.service.spec.ts, src/aurelia-slickgrid/services/resizer.service.ts
- instead of pulling gridId from grid options and then get grid DOM element, we can use the grid internal method "getContainerNode()" which gives us this info for free
=> refactor(service): cleanup code of Resizer Service and use grid methods

package.json, src/aurelia-slickgrid/global-grid-options.ts, src/aurelia-slickgrid/models/gridOption.interface.ts, src/aurelia-slickgrid/services/sort.service.ts, src/examples/slickgrid/example1.ts, test/cypress/integration/example01.spec.js, test/cypress/package.json
- when clearing sorting, the default is to use as sort is "id". This new grid option allows to provide another field id.
=> feat(sort): add default sort field as grid option

src/aurelia-slickgrid/services/__tests__/utilities.spec.ts, src/aurelia-slickgrid/services/utilities.ts
- when using both together, 1 was cancelling the other. To fix this, I rewrote the code use text split by the decimal and then recombining them as a new text with necessary thousand & decimal separators
with updated code, the result is now as shown below
1. first column has `thousandSeparator: '.'` and `decimalSeparator: ','`
2. second column has `thousandSeparator: ','` and `decimalSeparator: '.'`
=> fix(formatters): decimalSeparator & thousandSeparator work tgt

package.json, src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/services/__tests__/resizer.service.spec.ts, src/aurelia-slickgrid/services/resizer.service.ts, src/aurelia-slickgrid/services/utilities.ts, src/examples/slickgrid/example11.ts, src/examples/slickgrid/example12.ts, src/examples/slickgrid/example13.ts, src/examples/slickgrid/example15.ts, src/examples/slickgrid/example16.ts, src/examples/slickgrid/example17.ts, src/examples/slickgrid/example18.ts, src/examples/slickgrid/example19.ts, src/examples/slickgrid/example2.ts, src/examples/slickgrid/example20.ts, src/examples/slickgrid/example21.ts, src/examples/slickgrid/example22.ts, src/examples/slickgrid/example23.ts, src/examples/slickgrid/example24.ts, src/examples/slickgrid/example25.ts, src/examples/slickgrid/example26.ts, src/examples/slickgrid/example3.ts, src/examples/slickgrid/example4.ts, src/examples/slickgrid/example5.ts, src/examples/slickgrid/example7.ts, src/examples/slickgrid/example8.ts, src/examples/slickgrid/example9.ts
- that was a temporary patch that was put in place to compensate for incorrect scrollbar measure happening in some browser like Chrome. This patch is no longer necessary since the bug was fixed in SlickGrid (core)
=> fix(resizer): remove scrollbar measure compensate patch

src/aurelia-slickgrid/filter-conditions/__tests__/stringFilterCondition.spec.ts, src/aurelia-slickgrid/filter-conditions/stringFilterCondition.ts
- when using OperatorType.empty or OperatorType.contains, they should do a comparison of passing when item contains the substring of search term
=> fix(filter): string filter should also work when using Contains

src/aurelia-slickgrid/extensions/__tests__/rowMoveManagerExtension.spec.ts, src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts, src/aurelia-slickgrid/extensions/rowMoveManagerExtension.ts, src/aurelia-slickgrid/models/rowDetailView.interface.ts, src/aurelia-slickgrid/models/rowMoveManager.interface.ts, src/aurelia-slickgrid/services/__tests__/extension.service.spec.ts, src/aurelia-slickgrid/services/excelExport.service.ts, src/aurelia-slickgrid/services/extension.service.ts, src/examples/slickgrid/example16.ts, test/cypress/integration/example16.spec.js, test/cypress/package.json
- now create column definition just by the enableRowMoveManager flag
- also keep row selection with dataview syncGridSelection
- latest slickgrid version also brought the usabilityOverride callback method that was added in RowMoveManager plugin
=> feat(extension): add latest slickgrid with RowMove improvements

src/aurelia-slickgrid/models/column.interface.ts, src/aurelia-slickgrid/sorters/__tests__/dateIsoSorter.spec.ts, src/aurelia-slickgrid/sorters/__tests__/numericSorter.spec.ts, src/aurelia-slickgrid/sorters/__tests__/sorterUtilities.spec.ts, src/aurelia-slickgrid/sorters/__tests__/stringSorter.spec.ts, src/aurelia-slickgrid/sorters/dateUtilities.ts, src/aurelia-slickgrid/sorters/numericSorter.ts, src/aurelia-slickgrid/sorters/sorterUtilities.ts, src/aurelia-slickgrid/sorters/stringSorter.ts
- this is an opt-in flag because it could bring unwanted behavior and for example it breaks the Row Detail UI when sorting undefined values, so user can opt-in but it's off by default
=> feat(sort): add valueCouldBeUndefined column flag to help sorting

src/aurelia-slickgrid/services/__tests__/filter.service.spec.ts, src/aurelia-slickgrid/services/filter.service.ts, src/examples/slickgrid/example13.ts
- just by changing the operator from a compound filter shouldn't do any search yet and shouldn't result to an empty grid, we should only start searching when there's a real value entered
=> fix(filter): when entering filter operator it shouldn't do any filtering

src/aurelia-slickgrid/models/column.interface.ts, src/aurelia-slickgrid/services/__tests__/filter.service.spec.ts, src/aurelia-slickgrid/services/__tests__/sort.service.spec.ts, src/aurelia-slickgrid/services/filter.service.ts, src/aurelia-slickgrid/services/sort.service.ts, src/styles.scss, test/cypress/package.json
- in certain occasion we don't know at hand which field name to use, we might just know depending on certain logic (e.g. if item dataContext has a product type "I" then use field "catalogNumber" but if it's type "P" use field "productCategoryNumber", ...)
=> feat(query): add queryFieldNameGetterFn callback know which field to use

src/aurelia-slickgrid/styles/_variables.scss, src/aurelia-slickgrid/styles/slick-bootstrap.scss, src/aurelia-slickgrid/styles/slick-plugins.scss, src/examples/slickgrid/example8.scss, test/cypress/integration/example08.spec.js
- when column is sortable, we now show a hint while hovering the column. It helps identify if the hovering column is sortable or not, if user doesn't want this behavior he can simply change the SASS variable to opacity of 0.
=> feat(style): add Sort icon hint on hover when column is sortable

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/extensions/gridMenuExtension.ts, src/aurelia-slickgrid/services/__tests__/shared.service.spec.ts, src/aurelia-slickgrid/services/shared.service.ts
- this command "Toggle Filter Row" disappeared if it happens to have the filter row hidden when calling translate. This PR fixes it but while fixing this, it was also found that the Filter row MUST be visible BEFORE calling the translation service else the filters don't get recreated and that is even worst.
The Filters MUST be shown BEFORE calling the translation (the lib will do show the header row by itself internally to counter this issue). If we aren't showing the Filters prior to a language change, this is what happens, filters aren't re-created
So the fix is to show the Filter row anytime the translation service is called (when switch language) as shown below. We show the header row then we translate
=> fix(gridMenu): the command "Toggle Filter Row" disappeared

package.json, src/aurelia-slickgrid/global-grid-options.ts
- there was a small issue in core lib when using "datasetIdPropertyName" other than "id" so update to latest SlickGrid version which has the fix
- change default grid options of Row Detail "useRowClick" property to false
=> fix(rowDetail): use latest SlickGrid version to fix issue with id

src/aurelia-slickgrid/services/export-utilities.ts
- in some cases the user might have a formatter without any value or a "field" that is not in the dataContext, this however shouldn't block the use of exportWithFormatter
=> fix(formatter): exportWithFormatter should work with undefined item prop

src/aurelia-slickgrid/models/fileType.enum.ts
- PDF and DOC are unsupported file type since there are no Exporter Services that exist for them, so they should be removed from acceptable file type formats
=> fix(export): remove unsupported file type

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/examples/slickgrid/example1.ts
- ref, this bug was mentioned in this Stack Overflow [question](https://stackoverflow.com/questions/61750596/angular-slickgrid-paginators-item-per-page-is-not-displayed-according-to-config)
=> fix(pagination): passing custom pagination sizes should work

package.json, src/aurelia-slickgrid/global-grid-options.ts, src/aurelia-slickgrid/models/gridMenu.interface.ts, src/examples/slickgrid/example9.ts, test/cypress/integration/example01.spec.js, test/jest.config.js
- add "headerColumnValueExtractor" callback in the global grid options to deal with grouped header titles
- also add 2 other new options "contentMinWidth" and "useClickToRepositionMenu"
- this requires a new SlickGrid core version with these new options
- requires this core lib [PR](https://github.com/6pac/SlickGrid/pull/491) be merged and released under a new version
=> fix(gridMenu): column picker list should include grouped header titles

src/aurelia-slickgrid/styles/slick-plugins.scss
- not an issue with Bootstrap but other frameworks like Bulma had this issue which it was overriding the SlickGrid cell-menu/context-menu styling because of these menus use generic css dropdown/dropup classes
=> fix(styling): cell/context menus get re-position below the grid

src/aurelia-slickgrid/services/__tests__/groupingAndColspan.service.spec.ts, src/aurelia-slickgrid/services/groupingAndColspan.service.ts
- after hiding/showing columns from ColumnPicker/GridMenu we need to re-create the header grouping titles
=> fix(header): re-create header grouping title after changing picker cols

src/aurelia-slickgrid/filters/selectFilter.ts
- when user is using only a single Locale, the Select Filter (single/multi) should use the Locale text instead of the translation text
=> fix(filter): Select Filter should use default locale without translation

src/aurelia-slickgrid/custom-elements/slick-pagination.html, src/aurelia-slickgrid/custom-elements/slick-pagination.ts, test/cypress/package.json
- I found out that the Bootstrap styling applied to the DOM element does not block clicks from it, the reason is because they are in fact `href` links which cannot by disabled (according to w3c specs), so it's better to check if action is enabled before proceeding with clicks
=> fix(pagination): disabled page buttons should not be clickable

src/aurelia-slickgrid/filters/compoundDateFilter.ts, src/aurelia-slickgrid/filters/compoundInputFilter.ts, src/aurelia-slickgrid/filters/compoundSliderFilter.ts, src/aurelia-slickgrid/services/__tests__/graphql.service.spec.ts, src/aurelia-slickgrid/services/__tests__/grid-odata.service.spec.ts, src/aurelia-slickgrid/services/grid-odata.service.ts
- grid presets should work with short/long operator names, basically StartsWith/EndsWith were not working correctly while a*/*z were working correctly, both options should work
=> fix(presets): compound filters operator not working correctly w/presets

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/headerMenuExtension.ts, src/aurelia-slickgrid/services/__tests__/sort.service.spec.ts, src/aurelia-slickgrid/services/sort.service.ts, test/cypress/integration/example05.spec.js
- when there is no more column to sort, we could resort by default sort id which would display dataset the way it was when it was first loaded
- ref SO question: https://stackoverflow.com/questions/62489108/angular-slickgrid-column-wise-remove-sort-option-not-working-properly
- also found that Clear Column Sort on a Local Grid was not trigger a "sortChanged" event while it should so that the Grid State is also notified
=> feat(sorting): header menu clear sort, reset sorting when nothing left

src/aurelia-slickgrid/editorValidators/floatValidator.ts, src/aurelia-slickgrid/editors/__tests__/floatEditor.spec.ts
- basically 0.3 and .3 should be both accepted, the second one wasn't and this PR fixes it
=> fix(editor): float validator should accept decimal even without 0 suffix

src/aurelia-slickgrid/editors/__tests__/autoCompleteEditor.spec.ts, src/aurelia-slickgrid/editors/__tests__/dualInputEditor.spec.ts, src/aurelia-slickgrid/editors/__tests__/floatEditor.spec.ts, src/aurelia-slickgrid/editors/__tests__/integerEditor.spec.ts, src/aurelia-slickgrid/editors/__tests__/longTextEditor.spec.ts, src/aurelia-slickgrid/editors/__tests__/textEditor.spec.ts, src/aurelia-slickgrid/editors/autoCompleteEditor.ts, src/aurelia-slickgrid/editors/dualInputEditor.ts, src/aurelia-slickgrid/editors/floatEditor.ts, src/aurelia-slickgrid/editors/integerEditor.ts, src/aurelia-slickgrid/editors/longTextEditor.ts, src/aurelia-slickgrid/editors/textEditor.ts
- we were already checking for null value but undefined is another possibility, so now it checks for null/undefined in isValueChanged() method
=> fix(editor): shouldn't call cell changed when cell value is undefined

src/aurelia-slickgrid/editors/__tests__/dateEditor.spec.ts, src/aurelia-slickgrid/editors/dateEditor.ts, src/aurelia-slickgrid/models/column.interface.ts, src/examples/slickgrid/example3.ts
- we now have 3 available types to use with the Date Editors formatting
1. `type` (data input format),
2. `outputType` (picker display format)
3. `saveOutputType` (save format)
=> fix(editors): add saveOutputType to finally have proper save format

src/aurelia-slickgrid/styles/_variables.scss, src/aurelia-slickgrid/styles/slick-pagination.scss
- using SASS variable in `calc` should be interpolate with `#{}` like `calc(#{sass-var}-2px)`
- fixes new bug found from previous PR #385
=> fix(styling): sass variable should be interpolate before using calc

src/aurelia-slickgrid/services/extension.service.ts
- On line 314, instead of checking for ExtensionName.draggableGrouping, code is checking for ExtensionName.rowDetailView, due to which if the rowDetailVIew is on then draggableGrouping can't be on. This is causing the issue when we enable both.
=> fix(extensions): draggable grouping called wrong check

src/aurelia-slickgrid/constants.ts, src/aurelia-slickgrid/editorValidators/integerValidator.ts, src/aurelia-slickgrid/editorValidators/textValidator.ts, src/aurelia-slickgrid/editors/__tests__/autoCompleteEditor.spec.ts, src/aurelia-slickgrid/editors/__tests__/longTextEditor.spec.ts, src/aurelia-slickgrid/editors/__tests__/textEditor.spec.ts, src/aurelia-slickgrid/editors/autoCompleteEditor.ts, src/aurelia-slickgrid/editors/longTextEditor.ts, src/aurelia-slickgrid/editors/textEditor.ts, src/aurelia-slickgrid/models/columnEditor.interface.ts, src/aurelia-slickgrid/styles/_variables.scss, src/aurelia-slickgrid/styles/slick-editors.scss, src/examples/slickgrid/example26.ts
- add a text length counter (currentTextLength/maxLength) to the LongText Editor
- the new `minLenght`, `maxLength` options can be used by the following Editors (autoComplete, longText, text)
- also flip the position of the Cancel/Save buttons, Cancel should be on the left and Save on the right
=> feat(editors): add min/max length options to text editors

src/aurelia-slickgrid/extensions/__tests__/contextMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/contextMenuExtension.ts
- seems like it was working only when "enableTranslate" was active, it should now work in both cases with/without translations
=> fix(extensions): adding Context Menu custom commands was not working

src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts
- refresh of each row detail not happening correctly with "datasetIdPropName", this was due to the fact that the View is saved as a "CreatedView" interface and that is kept with "id" not with "datasetIdPropName"
- found out that I made a mistake when adding the `datasetIdPropName`, I keep the View with an `id` not with the dynamic `datasetIdPropName` and so I was keeping all the Views with `undefined` instead of their correct associated `id` (or custom `id`)... long story short, the refresh of each Row Detail wasn't working correctly with using a custom Id with `datasetIdPropName`
- fixes #546
=> fix(extensions): Row Detail not always refreshing with customId

src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts
- it seems that when trying to find the DOM element of the row detail, we should always use the last one instead of the first one found
=> fix(extension): Row Detail gets blanked out for no reason

src/aurelia-slickgrid/editors/autoCompleteEditor.ts
- it was throwing an error when the item dataContext did not have the label (or custom label) property inside the item dataContext
=> fix(editors): AutoComplete Editor might have undefined object label

src/aurelia-slickgrid/editors/selectEditor.ts
- when using boolean with a SingleSelect Editor, the `false` value was not being selected when it should
=> fix(editor): SingleSelect Editor should show pick false value

package.json
- fixes issue found in the `excel-builder-webpacker` npm package with the new Aurelia CLI 2.0 reported here: https://github.com/ghiscoding/aurelia-slickgrid-demos/issues/2
- this new major version was compiled with `ncc` and we now use the compiled `dist/index` instead of the uncompiled `src/index`
=> fix(core): use latest excel-builder-webpacker to fix CLI 2.0

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.html, src/examples/slickgrid/custom-footer.ts, src/examples/slickgrid/example29.html, src/examples/slickgrid/example29.ts, src/examples/slickgrid/index.ts, test/cypress/integration/example29.spec.js
this adds named slots for a custom header and footer so that more complex scenarios can be injected as part of the aurelia-slickgrid custom element
related issue https://github.com/ghiscoding/aurelia-slickgrid/issues/424
=> feat(slots):adds named slots for header and footer 

src/aurelia-slickgrid/editors/__tests__/selectEditor.spec.ts, src/aurelia-slickgrid/editors/selectEditor.ts, src/aurelia-slickgrid/filters/__tests__/selectFilter.spec.ts, src/aurelia-slickgrid/filters/selectFilter.ts, src/aurelia-slickgrid/models/collectionOption.interface.ts
- add 2 new methods (`addCustomFirstEntry`, `addCustomLastEntry`) to optionally add entry on both end of the collection
=> feat(core): add custom entry to Select Editor/Filter collections

src/aurelia-slickgrid/filter-conditions/__tests__/dateIsoFilterCondition.spec.ts, src/aurelia-slickgrid/filter-conditions/executeMappedCondition.ts, test/tsconfig.spec.json
- if we pass a Date object that has time and we use a dateIso format, or any other without time, we should disregard the time portion when using the CompoundDate Filter
=> fix(filters): disregard time when filtering date only format

src/aurelia-slickgrid/editors/selectEditor.ts, src/aurelia-slickgrid/filters/selectFilter.ts, src/examples/slickgrid/example6.ts
- when using "addBlankEntry" or "addCustomFirstEntry", the SelectFilter was affecting SelectEditor (and vice versa) because the collection was used by ref, so to fix this we can just do a copy of the collection before dealing with it
=> fix(select): make a collection array copy to avoid change by ref

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/styles/_variables.scss, test/cypress/package.json
- a regression was observer when using GridState/GridPresets with Local Storage, whenever clearing a Filter, it would put back the preset filter.
=> fix(filters): tree data presets caused regression in any grid w/presets

src/aurelia-slickgrid/models/gridOption.interface.ts
just adds a bit more info that the actual filter row is affected by this option
=> docs(options): improve showHeaderRow jsdoc

package.json, src/aurelia-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/gridMenuExtension.ts, src/aurelia-slickgrid/extensions/headerMenuExtension.ts, src/examples/slickgrid/example14.ts, src/examples/slickgrid/example20.ts, src/examples/slickgrid/example25.ts
- the `alwaysShowVerticalScroll` flag should be dealt directly in the core and it should never show vertical scroll on left frozen container, even when the `alwaysShowVerticalScroll` is set to True (see core lib [PR #537](6pac/SlickGrid#537))
- requires core lib [PR #537](6pac/SlickGrid#537) to be merged and released
=> fix(core): don't override alwaysShowVerticalScroll flag

src/aurelia-slickgrid/models/gridStateChange.interface.ts
- Both the service and the tests use the CurrentColumn type for the event GridStateType.column
=> fix(interfaces): column types in GridStateChange

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- when jQuery mousewheel is imported, SlickGrid attaches a scroll handler which prevent scrolling to work as normal, this however should only be used with frozen grids since it creates other issues like seen in Row Detail were it doesn't behave correctly
- NOTE that this is more of a patch and a SlickGrid grid option flag would be better to handle that, possibly create a flag in future SlickGrid version
- this is a patch until a better implementation is done into SlickGrid (by adding an extra flag into the the grid option to disable on the fly even when jquery mousewheel is loaded)
- ref Angular-Slickgrid issue [#618](https://github.com/ghiscoding/Angular-Slickgrid/issues/618)
=> fix(extensions): import jQuery mousewheel only with frozen

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/services/pagination.service.ts, src/examples/slickgrid/example5.html, src/examples/slickgrid/example5.ts, test/cypress/integration/example05.spec.js
- add a new paginationOptions getter/setter to avoid incomplete gridOptions passed by the OData result callback, merging the gridOptions was incomplete because it was only merging with the local gridOptions instead of the local+global gridOptions
- basically we won't be able to see the Empty Dataset Warning with OData unless we modified the code and use the new setter. Keeping the old code will still work but just won't display the warning when dataset is empty
=> fix(backend): OData/GraphQL pagination should display warning on empty

src/aurelia-slickgrid/formatters/__tests__/alignRightFormatter.spec.ts, src/aurelia-slickgrid/formatters/__tests__/centerFormatter.spec.ts, src/aurelia-slickgrid/formatters/__tests__/treeFormatter.spec.ts, src/aurelia-slickgrid/formatters/__tests__/yesNoFormatter.spec.ts, src/aurelia-slickgrid/formatters/alignRightFormatter.ts, src/aurelia-slickgrid/formatters/centerFormatter.ts, src/aurelia-slickgrid/formatters/index.ts
- center already existed but we can add `alignCenter` to be in line with the other `alignRight` Formatter
- note also that there's no need for `alignLeft` since everything is aligned to the left in SlickGrid
=> feat(formatters): add AlignRight and AlignCenter Formatters

src/aurelia-slickgrid/models/hideColumnOption.interface.ts, src/aurelia-slickgrid/models/index.ts, src/aurelia-slickgrid/services/__tests__/grid.service.spec.ts, src/aurelia-slickgrid/services/grid.service.ts, src/examples/slickgrid/example16.ts
- deprecated previous methods (`hideColumn`, `hideColumnByIndex`) since the new methods offer more values with extra options to resize and/or hide from pickers
=> feat(services): add 2x new methods hideColumnById(s)

package.json, src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/gridMenuExtension.ts, src/aurelia-slickgrid/extensions/headerMenuExtension.ts, src/aurelia-slickgrid/models/gridOption.interface.ts
- this enables the use of the mousewheel scrolling event handler and that makes the mousewheel scroll to work from anywhere in the grid
- implement a permanent fix for issue #618 to replace temp fix made in PR #619
- requires the core lib [PR #555](https://github.com/6pac/SlickGrid/pull/555) to be merged and released
=> feat(core): add enableMouseWheelScrollHandler grid option

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/extensions/__tests__/columnPickerExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/extensionUtility.spec.ts, src/aurelia-slickgrid/extensions/__tests__/gridMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts, src/aurelia-slickgrid/extensions/columnPickerExtension.ts, src/aurelia-slickgrid/extensions/extensionUtility.ts, src/aurelia-slickgrid/extensions/gridMenuExtension.ts, src/aurelia-slickgrid/extensions/headerMenuExtension.ts, src/aurelia-slickgrid/services/__tests__/shared.service.spec.ts, src/aurelia-slickgrid/services/shared.service.ts, test/cypress/integration/example20.spec.js
- when calling "hide column" we need to readjust the freezingColumn by (-1) when on left container
- when showing/hiding a column from ColumnPicker/GridMenu, we need to check if we need to also readjust when column is on the left container
=> fix(core): showing/hiding column shouldn't affect its freezing position

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- all Editors/Filters are using the column definition id to add a css className for properly identifying the this editor/filter with a unique className, however if the columnId includes a dot then that becomes 2 class names in css and will cause issues, so it's better to advise the user from the start that his column definitions has some invalid Id(s).
=> fix(core): add console error if any of column def id includes dot

src/aurelia-slickgrid/services/container.service.ts
- when we were coming from another page, the basic Slickgrid-Universal `containerService` was acting funny, the fix is to register it in as singleton but only in the immediate container
=> fix(components): Composite Editor Clone was sometime throwing error

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- this issue was reported in Angular-Slickgrid with the following: using `dataView.onRowsOrCountChanged` instead of `dataView.onRowCountChanged` to refresh metrics this refreshes the whole grid in the case of an `updateItemById`.
=> fix(metrics): use `onRowCountChanged` event to refresh metrics

src/aurelia-slickgrid/constants.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/global-grid-options.ts, src/examples/slickgrid/example13.ts, src/examples/slickgrid/example18.ts
- we previously had the `filterTypingDebounce` but that was only available when using `BackendServiceApi` (with OData/GraphQL) but this PR goes further and makes it available to any type of grids, so it can now be used with a local grid (JSON dataset)
- we also move the debounce code from the Filter Service into each filter component itself (only the following 2 filters requires this, `InputFilter` and `CompoundInputFilter`). The Filter Service shouldn't do any debounce, it should be the responsability of the concerned filter and that is what we refactored in this PR as well.
=> feat(filters): add optional `filterTypingDebounce` for filters w/keyup

src/aurelia-slickgrid/services/resizer.service.ts
=> fix(resizer): allow gridHeight/Width to be passed as string, fixes #284

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- loading of Columns Grid Presets should only be done once (before resizing) and loading Filters Grid Presets could be done one or more times, so to fix this I have separated `loadPresetsWhenDatasetInitialized` into 2 new methods and made sure to call the columns grid preset only once.
- this issue was identified while porting the previous PR #341 into Angular-Slickgrid
=> fix(presets): loading columns presets should only be done once

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- resizer service init must be done only after SlickGrid is initialized, else we end up binding our resize to a grid dom element that doesn't yet exist in the DOM
- this regression bug wasn't caught earlier because there's no Cypress E2E to test that since it's too hard to test, basically it was caught manually since I found out the auto-resize stopped working (it failed silently) and I was wondering why that suddenly happened
=> fix(resizer): fix a regression bug caused by previous PR

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- with Tree Data only supporting single sort, I found out that we could bypass the single sort by using the header menu
- also found that sort presets with multiple columns were also loading as multiple sort even when the multiColumnSort is disabled and now it's fixed
=> fix(sorting): multi-column sort shouldn't work when option is disabled

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, test/cypress/integration/example06.spec.js
- the backend services were using SlickGrid `getColumns` to get the column definitions but that returns only the visible columns, however we should be able to preset filters on hidden columns and also expect all columns to be queried (it's not because the column is hidden that we shouldn't be able to filter it and query it)
=> fix(backend): able to preset filters on hidden columns & all queried

.github/workflows/main.yml
- we shouldn't refresh (publish) GitHub demo page on every PR merge, we should instead only redeploy on a release of a new version
=> chore(ci): only deploy GitHub page demo on master & commit is a release

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-utilities.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid-utilities.ts
- basically if our Custom Editor Formatter is already in the column definitions and we re-ran `autoAddEditorFormatterToColumnsWithEditor` method for any reasons (this happen when changing column definitions via its setter) then we want to make sure that we don't add the same formatter over and over
below is an example of the bug when it happens, we can see the editor formatter (the cell with outlines) are added multiple times and show multiple outlines
and after the fix, we now see the outline only once because the editor formatter will never be added more than once
=> fix(formatters): shouldn't auto-add editor formatter multiple times

src/aurelia-slickgrid/index.ts, src/aurelia-slickgrid/models/formatter.interface.ts, src/aurelia-slickgrid/models/index.ts, src/examples/slickgrid/example12.ts, src/examples/slickgrid/example24.ts
- it's already available in Slickgrid-Universal so no need to duplicate this interface
=> chore: remove unnecessary Formatter interface

src/aurelia-slickgrid/custom-elements/slick-pagination.ts, test/cypress/integration/example10.spec.js
- we should be able to toggle Pagination and it should still work as expected after showing it again
- the previous code was disposing of the Pagination Service when hiding (disposing) the Pagination Component but that shouldn't be the case, disposing of the Service should strictly be handled by the Angular-Slickgrid-Component
=> fix(pagination): should be able to toggle Pagination

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, src/aurelia-slickgrid/custom-elements/slick-pagination.ts
By default, aurelia webpack plugin won't look for html in a mono repository `node_modules` folder.
This change will allow for usage in mono repositories without additional webpack configuration.
=> fix(aurelia-slickgrid): reference html explicitly

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- fixes a problem only reported in Angular-Slickgrid, not in Aurelia-Slickgrid but might as well apply the same code
=> fix(grid): invalidate grid after setItems to re-render grid

test/cypress/integration/example30.spec.js
- fix an issue in Slickgrid-Universal which we found that if we Edit a value (let say Title to "Task 1234") and then do a Mass Update on different field (say "% Complete" to 90%), the mass update was actually picking up the "Task 1234" from the previous edit even though it wasn't part of the Mass Update. So we can simply clear the `formValues` object when opening the modal window and before populating the form
=> fix(composite): calling Edit change shouldn't affect Mass-Update

test/cypress/package.json, test/cypress/tsconfig.json, test/cypress/yarn.lock
- had to stick with Cypress 7.x for so long only to find out that the reason Cypress 9.x didn't work was because of `tsconfig.json` file having an invalid path inside it
=> chore(tests): fix issue found with latest Cypress version

package.json, src/examples/slickgrid/example34.ts, yarn.lock
- previous Faker lib was destroyed by its own author and new recommentation is to use @faker-js/faker which is now driven by the community and is the new official lib
=> chore(deps): replace Faker by official @faker-js/faker

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- should throw if 1 of these 2 are missing ``gridOptions` and/or `columnDefinitions`
=> fix(core): throw error when `gridOptions` missing in View

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, yarn.lock
- replicate issue found and fixed in Slickgrid-Universal [PR 742](https://github.com/ghiscoding/slickgrid-universal/pull/742)
=> fix(collectionAsync): hidden column does not load edit field selection

src/examples/slickgrid/example30.html, src/examples/slickgrid/example30.ts
- the cell orange outline, which tells us the cell wasn't saved yet, should follow the row for both cases of a filter and/or pagination change
- the previous implementation was also not always working to remove all edit cell styling, it works a lot better by keeping a styling queue with the a style key and to remove all styles we simply loop through that queue
=> fix(demo): edit outline should follow on filter/pagination changed

package.json, yarn.lock
- having `i18next` as `peerDependencies` requires the developer to always install it even if the user doesn't use translations, if we move it as a regular `dependencies`, it should install it silently without forcing the user to install it (at least I think so)
=> fix(deps): move i18next as regular dependencies to avoid fulll install

src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid.spec.ts, src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts, test/cypress/e2e/example15.cy.js
- the steps to reproduce the issue was to create a grid with `frozenColumn` in the grid options, then change column position (cols reordering) and finally open header menu and freeze any of the column and the bug was that it was going back to original positions while it should keep new positions and just add new freeze column
=> fix(pinning): cols reorder & freezing shouldn't affect order

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- calling `datasetHierarchical` setter shouldn't cause scroll flickering, this was caused a call to the DataView `setItems` with an empty array which in terms always scroll back to top and that was meant to clear the dataset before recreating it, however this is certainly not needed since calling the `datasetHierarchical` setter will then trigger a new sort which will indirectly call DataView setItems anyway
=> fix: adding dataset hierarchical item shouldn't cause scroll flickering

.github/workflows/main.yml, package.json, src/aurelia-slickgrid/tsconfig.build.json, src/aurelia-slickgrid/value-converters/asgDateFormat.ts, src/examples/resources/value-converters/date-format.ts, src/examples/slickgrid/example23.ts, src/examples/slickgrid/example6.ts, test/jest.config.ts, test/tsconfig.spec.json, tsconfig.json, tsconfig.spec.json
- build only 1 `dist/types` folder for all target
- previous implementation didn't pass all type exports as can be shown in [Are the types wrong?](https://arethetypeswrong.github.io)
=> fix: improve build & types exports for all targets, Node, CJS/ESM

src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- partially rolls back PR #1118 because that caused a regression that was identified by a user of Angular-Slickgrid in which defining a global external resource for ExcelExport no longer worked.
- this PR also fixes duplicatation of external resources when having multiple grid on the same page and spreading grid options of another grid (e.g.: `{ ...this.gridOptions1, sortable: false }`)
=> fix: spreading 2 grids options causes duplicate ext resources

packages/aurelia-slickgrid/src/services/aureliaUtil.service.ts, packages/aurelia-slickgrid/src/services/translater.service.ts
when using a single locale, we should be able to skip the use of I18N altogether and not have to register it. This should fix the single locale demo that was not yet working
=> fix: I18N could be optional when providing single locale

docs/column-functionalities/filters/custom-filter.md, docs/migrations/migration-to-2.x.md, packages/demo/src/examples/slickgrid/custom-aureliaViewModelEditor.ts, packages/demo/src/examples/slickgrid/custom-aureliaViewModelFilter.ts, packages/demo/src/examples/slickgrid/example23.ts, packages/demo/src/examples/slickgrid/example26.ts, packages/demo/src/examples/slickgrid/example4.ts
- the Filter `model` prop should be a constructor and it shouldn't newed (instantiated), it was defined like so in the docs and Wikis but that was actually wrong
- ref Slickgrid-Universal [PR 1430](https://github.com/ghiscoding/slickgrid-universal/pull/1430)
=> fix: Filter `model` is now `FilterConstructor` and shouldn't be newed

packages/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts, packages/demo/src/examples/slickgrid/custom-aureliaViewModelEditor.ts, packages/demo/src/examples/slickgrid/custom-inputEditor.ts, packages/demo/src/examples/slickgrid/example3.ts
- users can still call `internalColumnEditor` but since it's deprecated, then it's better to remove it from all demos
=> chore: remove deprecated `internalColumnEditor` usage

packages/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts
- always committing as soon as we do focusout/blur is a little extreme since in some cases we for example clicking on an editor with a picker is closing the picker before we even a chance to choose anything
=> fix: we shouldn't always commit on focusout/blur

docs/column-functionalities/editors.md, docs/column-functionalities/editors/select-dropdown-editor.md, docs/column-functionalities/filters/select-filter.md, docs/column-functionalities/formatters.md, docs/developer-guides/csp-compliance.md, docs/getting-started/quick-start.md, packages/aurelia-slickgrid/package.json, packages/aurelia-slickgrid/src/extensions/__tests__/slickRowDetailView.spec.ts, packages/aurelia-slickgrid/src/extensions/slickRowDetailView.ts, packages/demo/package.json, packages/demo/src/main.ts, pnpm-lock.yaml
- replace `isomorphic-dompurify` with `dompurify` and make it a dev deps
=> feat!: make DOMPurify as optional

packages/demo/src/examples/slickgrid/example27.html, packages/demo/src/examples/slickgrid/example27.ts
- prior to this PR, calling `addItem()`, or `addItems()`, was always resorting using the Tree Data initial sort because the method being called is the same for the first build of the Tree Data and/or adding an item. So when we're adding an item, we should really reuse any existing sort that may exist when resynching the flat/hierarchical and resorting them (we always need to resort whenever it changes because by SlickGrid doesn't support Tree Data, we only support it by keeping copies of both flat & hierarchical and then resort them whenever something changes)
=> fix(TreeData): addItem should keep current sorted column

docs/grid-functionalities/grouping-aggregators.md
https://docs.aurelia.io/developer-guides/migrating-to-aurelia-2#binding-commands
> .delegate command has been removed, use .trigger instead.
Else, I'm encountering this error
```
Uncaught (in promise) Error: AUR0009: Attempted to jitRegister something that is not 
a constructor: 'au:resource:binding-command:delegate'. Did you forget to register this resource?
```
Maybe there are more instances of "delegate" in the docs, but haven't looked for them.
For now, I just wanted to update this particular instance
Regards
=> docs(groups): replace "delegate" with "trigger

packages/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts
- we should be able to use Aurelia-Slickgrid custom element without providing any grid options
=> feat: allow using AureliaSlickgrid component w/o grid options

packages/aurelia-slickgrid/package.json, packages/demo/package.json, packages/demo/src/examples/slickgrid/example23.ts, pnpm-lock.yaml
the package [copyfiles](https://www.npmjs.com/package/copyfiles) isn't supported anymore (hasn't been for a few years), though we can use simple NodeJS native API to rewrite the whole thing as [native-copyfiles](https://www.npmjs.com/package/native-copyfiles) which is much simpler and only has 1 single dependency to `tinyglobby`.
=> chore: replace copyfiles with a in-house native package
