ghiscoding/aurelia-slickgrid

- aurelia-slickgrid/package.json
- aurelia-slickgrid/src/aurelia-slickgrid/global-grid-options.ts
- aurelia-slickgrid/src/aurelia-slickgrid/models/gridOption.interface.ts
- aurelia-slickgrid/src/aurelia-slickgrid/services/controlAndPlugin.service.ts
- aurelia-slickgrid/src/aurelia-slickgrid/styles/slick-bootstrap.scss
- aurelia-slickgrid/src/examples/slickgrid/example6.html
- aurelia-slickgrid/src/examples/slickgrid/example6.ts
- package.json
> fix(grid): issue #44, sort icon hidden behind grid menu w/small dataset

- aurelia-slickgrid/src/aurelia-slickgrid/models/column.interface.ts
- aurelia-slickgrid/src/aurelia-slickgrid/services/controlAndPlugin.service.ts
- aurelia-slickgrid/src/examples/slickgrid/example3.ts
- client-cli/src/examples/slickgrid/example3.js
- doc/github-demo/src/examples/slickgrid/example3.ts
- [Wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Header-Menu-&-Header-Buttons#how-to-exclude-header-menu-from-a-particular-column) updated
> fix(headerMenu): we should not display header menu on row select column

- aurelia-slickgrid/src/aurelia-slickgrid/filters/compoundDateFilter.ts
- aurelia-slickgrid/src/aurelia-slickgrid/filters/compoundInputFilter.ts
- aurelia-slickgrid/src/aurelia-slickgrid/filters/singleSelectFilter.ts
- aurelia-slickgrid/src/examples/slickgrid/example12.ts
- client-cli/src/examples/slickgrid/example12.js
- doc/github-demo/src/examples/slickgrid/example12.ts
On the Example 12 if you set the column "completed" filter to True/False it works but if you set it back to nothing it should return the entire set however nothing was returned.
> fix(filter): SingleSelect Filter (& others) should return all when empty

- ISSUE_TEMPLATE.md
- aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts
- aurelia-slickgrid/src/examples/slickgrid/example13.ts
Closes issue #90
- also added complete set of Filters to the Grouping Example
> fix(grouping): Filter & Grouping should work together, closes #90

- aurelia-slickgrid/src/aurelia-slickgrid/editors/dateEditor.ts
- aurelia-slickgrid/src/aurelia-slickgrid/editors/longTextEditor.ts
- aurelia-slickgrid/src/aurelia-slickgrid/editors/selectEditor.ts
- aurelia-slickgrid/src/aurelia-slickgrid/editors/sliderEditor.ts
- without this, it was going into an infinite loop
> fix(autocommit): auto-commit should not save if field is invalid

- aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts
- aurelia-slickgrid/src/aurelia-slickgrid/editors/selectEditor.ts
- aurelia-slickgrid/src/aurelia-slickgrid/filters/nativeSelectFilter.ts
- aurelia-slickgrid/src/aurelia-slickgrid/filters/selectFilter.ts
- aurelia-slickgrid/src/aurelia-slickgrid/formatters/collectionEditorFormatter.ts
- aurelia-slickgrid/src/aurelia-slickgrid/models/columnEditor.interface.ts
- aurelia-slickgrid/src/aurelia-slickgrid/models/columnFilter.interface.ts
- aurelia-slickgrid/src/aurelia-slickgrid/services/resizer.service.ts
- aurelia-slickgrid/src/examples/slickgrid/example4.ts
- prior to this only collection of value/label pair was accepted.
> feat(select): collection can also be of type String

- aurelia-slickgrid/package.json
- aurelia-slickgrid/src/aurelia-slickgrid/models/checkboxSelector.interface.ts
- aurelia-slickgrid/src/aurelia-slickgrid/styles/slick-plugins.scss
- aurelia-slickgrid/src/examples/slickgrid/example10.ts
- aurelia-slickgrid/src/examples/slickgrid/example5.ts
- doc/github-demo/src/examples/slickgrid/example10.ts
- doc/github-demo/src/examples/slickgrid/example5.ts
- package.json
Bring possibility to change "Select All" checkbox location (on the Filter row or on the Column Header)
> feat(selector): add new property to display Select All chkbox elsewhere

- aurelia-slickgrid/src/aurelia-slickgrid/filters/selectFilter.ts
- aurelia-slickgrid/src/aurelia-slickgrid/models/filter.interface.ts
- aurelia-slickgrid/src/aurelia-slickgrid/services/filter.service.ts
- add code in place to know if the Filter was rendered more than 1x time
> fix(filter): Select Filter "addBlankEntry" sometimes add 2x entries

- aurelia-slickgrid/src/aurelia-slickgrid/filters/index.ts
- aurelia-slickgrid/src/aurelia-slickgrid/filters/inputFilter.ts
- aurelia-slickgrid/src/aurelia-slickgrid/filters/inputMaskFilter.ts
- aurelia-slickgrid/src/aurelia-slickgrid/formatters/maskFormatter.ts
- aurelia-slickgrid/src/examples/slickgrid/example2.ts
- aurelia-slickgrid/src/examples/slickgrid/example9.ts
- this is a quick & easy input mask filter support without any 3rd party lib relience
- if user want a full featured mask input, then it's better to use an external lib and build their own custom filter
> feat(filter): input mask filter

- aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts
- aurelia-slickgrid/src/aurelia-slickgrid/services/filter.service.ts
- aurelia-slickgrid/src/aurelia-slickgrid/services/graphql.service.ts
- aurelia-slickgrid/src/aurelia-slickgrid/services/grid-odata.service.ts
- also make the ENTER key work and it should skip debounce waiting time and query right away
> fix(backend): debounceTypingDelay on input Filter was no longer working

- aurelia-slickgrid/src/aurelia-slickgrid/services/grid.service.ts
- aurelia-slickgrid/src/examples/slickgrid/example11.ts
- doc/github-demo/src/examples/slickgrid/example11.ts
- add new methods "deleteDataGridItems" and "deleteDataGridItemByIds"
- add 3rd argument "shouldHighlightRow" boolean field to the "updateDataGridItem" ans "updateDataGridItems" method
> feat(gridService): add new methods to GridService

- aurelia-slickgrid/src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts
- aurelia-slickgrid/src/aurelia-slickgrid/models/aureliaViewOutput.interface.ts
- aurelia-slickgrid/src/aurelia-slickgrid/models/index.ts
- aurelia-slickgrid/src/aurelia-slickgrid/services/aureliaUtilService.ts
- the issue was that Row details is getting added multiple times after scrolling to the end and back on top
> fix(rowDetail): clear Row Detail content before recreating it

- .editorconfig
- src/examples/slickgrid/example21.html
- src/examples/slickgrid/example21.ts
- closes #152 
- show how to do a single search outside of the grid
> feat(filter): add demo of single search filter, closes #152

- .vscode/launch.json
- src/aurelia-slickgrid/services/__tests__/collection.service.spec.ts
- src/aurelia-slickgrid/services/__tests__/gridState.service.spec.ts
- src/aurelia-slickgrid/services/__tests__/resizer.service.spec.ts
- src/aurelia-slickgrid/services/__tests__/utilities.spec.ts
- src/aurelia-slickgrid/services/extension.service.ts
- src/aurelia-slickgrid/services/gridState.service.ts
- add GridState Service full test suite
> fix(gridState): columnPicker & gridMenu not triggering gridState change

- src/aurelia-slickgrid/extensions/checkboxSelectorExtension.ts
- src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts
- src/aurelia-slickgrid/models/column.interface.ts
- src/examples/slickgrid/example16.ts
- excludeFromColumnPicker for the Column Picker
- excludeFromGridMenu for the Grid Menu
> feat(menu): add options to exclude column titles from Menus

- src/aurelia-slickgrid/services/__tests__/resizer.service.spec.ts
- src/aurelia-slickgrid/services/resizer.service.ts
- src/examples/slickgrid/example2.html
- src/examples/slickgrid/example2.ts
- also return the window event when calling the event aggregator "asg:onBeforeResize"
> feat(resizer): add new method "pauseResizer"

- package.json
- src/aurelia-slickgrid/index.entry.spec.ts
- src/aurelia-slickgrid/models/backendService.interface.ts
- src/aurelia-slickgrid/models/filter.interface.ts
- src/aurelia-slickgrid/services/__tests__/filter.service.spec.ts
- src/aurelia-slickgrid/services/backend-utilities.ts
- src/aurelia-slickgrid/services/filter.service.ts
- src/aurelia-slickgrid/services/sort.service.ts
- src/custom_typings/global.d.ts
- src/examples/slickgrid/example13.ts
- src/typings/global.d.ts
- tslint.json
- refactor SortService to use a common backend function used by FilterService as well
> feat(tests): add more unit tests to FilterService

- src/aurelia-slickgrid/models/odataOption.interface.ts
- src/aurelia-slickgrid/services/__tests__/odataQueryBuilder.service.spec.ts
- src/aurelia-slickgrid/services/odataQueryBuilder.service.ts
- src/examples/slickgrid/example3.html
- src/examples/slickgrid/example5.html
- src/examples/slickgrid/example5.ts
- test/cypress/integration/example5.spec.js
- test/cypress/integration/example6.spec.js
- update Jest unit tests
- update Cypress E2E tests
- ref Angular-Slickgrid [PR #291](https://github.com/ghiscoding/Angular-Slickgrid/pull/291)
animated gif preview of the changes
> feat(odata): add "enableCount" flag to add to OData query

- src/aurelia-slickgrid/services/__tests__/grid-odata.service.spec.ts
- src/aurelia-slickgrid/services/grid-odata.service.ts
- Angular-Slickgrid ref issue [#328](https://github.com/ghiscoding/Angular-Slickgrid/issues/328)
> fix(odata): filter with single quote should be escaped

- src/aurelia-slickgrid/services/__tests__/grid-odata.service.spec.ts
- src/aurelia-slickgrid/services/grid-odata.service.ts
Angular-Slickgrid issue ref [#340](https://github.com/ghiscoding/Angular-Slickgrid/issues/340)
> fix(odata): no quote escape required for IN operator w/non-string column

- package.json
- typings.json
> (fix) gulp dependency and typings fix

- README.md
- src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts
- src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- src/aurelia-slickgrid/models/backendEventChanged.interface.ts
- src/aurelia-slickgrid/models/backendServiceApi.interface.ts
- src/aurelia-slickgrid/models/graphqlPaginatedResult.interface.ts
- src/aurelia-slickgrid/models/index.ts
- src/aurelia-slickgrid/services/__tests__/backend-utilities.spec.ts
- src/aurelia-slickgrid/services/__tests__/graphql.service.spec.ts
- src/aurelia-slickgrid/services/backend-utilities.ts
- src/aurelia-slickgrid/services/pagination.service.ts
- src/examples/slickgrid/example6.ts
- renamed previous `GraphqlResult` to `GraphqlPaginatedResult` and use `GraphqlResult` without Pagination info
> fix(graphql): add missing updated GraphqlResult interface

- src/aurelia-slickgrid/editors/sliderEditor.ts
- src/aurelia-slickgrid/filters/autoCompleteFilter.ts
- src/aurelia-slickgrid/filters/compoundDateFilter.ts
- src/aurelia-slickgrid/filters/compoundInputFilter.ts
- src/aurelia-slickgrid/filters/compoundSliderFilter.ts
- src/aurelia-slickgrid/filters/dateRangeFilter.ts
- src/aurelia-slickgrid/filters/inputFilter.ts
- src/aurelia-slickgrid/filters/nativeSelectFilter.ts
- src/aurelia-slickgrid/filters/selectFilter.ts
- src/aurelia-slickgrid/filters/sliderFilter.ts
- src/aurelia-slickgrid/services/excelExport.service.ts
- src/examples/slickgrid/custom-inputFilter.ts
- move the element IDs as CSS classes instead
> fix(filters): remove filter DOM element IDs to avoid duplicate IDs

- src/aurelia-slickgrid/models/currentRowSelection.interface.ts
- src/aurelia-slickgrid/services/__tests__/gridState.service.spec.ts
- src/aurelia-slickgrid/services/gridState.service.ts
- src/examples/slickgrid/example10.ts
- test/cypress/integration/example10.spec.js
- a new property "filteredDataContextIds" was added to handle possible filtered data with row selection
> fix(selection): filter data should work with row selection

- src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts
- src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- src/aurelia-slickgrid/services/__tests__/extension.service.spec.ts
- src/aurelia-slickgrid/services/extension.service.ts
- src/examples/slickgrid/custom-aureliaViewModelFilter.ts
- src/examples/slickgrid/example12.ts
- src/examples/slickgrid/example3.html
- src/examples/slickgrid/example3.ts
- adding comments that explain to user what to do when using row selection and adding column dynamically, user must use "getColumns"
> fix(columns): add/remove columns dynamically

- .circleci/config.yml
- src/aurelia-slickgrid/custom-elements/slick-pagination.ts
- src/aurelia-slickgrid/editors/longTextEditor.ts
- src/aurelia-slickgrid/editors/selectEditor.ts
- src/aurelia-slickgrid/extensions/contextMenuExtension.ts
- src/aurelia-slickgrid/extensions/extensionUtility.ts
- src/aurelia-slickgrid/extensions/gridMenuExtension.ts
- src/aurelia-slickgrid/extensions/headerMenuExtension.ts
- src/aurelia-slickgrid/filters/compoundInputFilter.ts
- src/aurelia-slickgrid/filters/selectFilter.ts
- src/aurelia-slickgrid/global-grid-options.ts
- src/aurelia-slickgrid/models/gridOption.interface.ts
- src/aurelia-slickgrid/services/__tests__/utilities.spec.ts
- src/aurelia-slickgrid/services/excelExport.service.ts
- src/aurelia-slickgrid/services/export.service.ts
- src/aurelia-slickgrid/services/utilities.ts
- src/main.ts
> feat(i18n): add namespace prefix + separator grid option, closes #338

- src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts
- src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- previous PR #334 caused a new small issue, were the header row is being shown when changing locale even when there are no Filters.
> fix(gridMenu): command "Toggle Filter Row" header row

- src/aurelia-slickgrid/index.ts
- every Filter have to be registered as Transient
- closes #345
> fix(filters): add all Filters as Transient, closes #345

- package.json
- src/aurelia-slickgrid/models/gridMenu.interface.ts
- also fixes an issue with grouping header not properly showing full browser vertical scroll
> feat(gridMenu): update to latest SlickGrid & add new Grid Menu options

- src/aurelia-slickgrid/editors/__tests__/dualInputEditor.spec.ts
- src/aurelia-slickgrid/editors/dualInputEditor.ts
- src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts
- src/aurelia-slickgrid/services/__tests__/utilities.spec.ts
- src/aurelia-slickgrid/services/filter.service.ts
- src/aurelia-slickgrid/services/grid.service.ts
- src/aurelia-slickgrid/services/treeData.service.ts
- src/aurelia-slickgrid/services/utilities.ts
- test/cypress/package.json
- do a search across the project and add "datasetIdPropertyName" everywhere that it was missing
> fix(core): add missing use of custom datasetIdPropertyName

- src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid-constructor.spec.ts
- src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- src/aurelia-slickgrid/extensions/__tests__/headerMenuExtension.spec.ts
- src/aurelia-slickgrid/extensions/headerMenuExtension.ts
- src/aurelia-slickgrid/services/__tests__/filter.service.spec.ts
- src/aurelia-slickgrid/services/__tests__/sort.service.spec.ts
- src/aurelia-slickgrid/services/filter.service.ts
- src/aurelia-slickgrid/services/sort.service.ts
- src/examples/slickgrid/example10.ts
- src/examples/slickgrid/example27.ts
- the Tree Data must execute pre-filtering with Tree Data when having Grid Preset Filters
> fix(filter): Grid Preset Filters should work with Tree Data View

- src/aurelia-slickgrid/editors/autoCompleteEditor.ts
- src/aurelia-slickgrid/filters/__tests__/compoundDateFilter.spec.ts
- src/aurelia-slickgrid/filters/__tests__/compoundInputFilter.spec.ts
- src/aurelia-slickgrid/filters/__tests__/compoundSliderFilter.spec.ts
- src/aurelia-slickgrid/filters/compoundDateFilter.ts
- src/aurelia-slickgrid/filters/compoundInputFilter.ts
- src/aurelia-slickgrid/filters/compoundSliderFilter.ts
- src/aurelia-slickgrid/filters/filterUtilities.ts
- src/aurelia-slickgrid/models/autocompleteOption.interface.ts
- src/aurelia-slickgrid/services/utilities.ts
- src/aurelia-slickgrid/styles/_variables-theme-material.scss
- src/aurelia-slickgrid/styles/_variables-theme-salesforce.scss
- src/aurelia-slickgrid/styles/_variables.scss
- src/aurelia-slickgrid/styles/slick-plugins.scss
- src/aurelia-slickgrid/styles/ui-autocomplete.scss
- also change Compound Filter styling
> feat(styling): add description to Compound Filter Operators

- src/aurelia-slickgrid/global-grid-options.ts
- src/aurelia-slickgrid/models/gridOption.interface.ts
- src/aurelia-slickgrid/services/groupingAndColspan.service.ts
- src/aurelia-slickgrid/styles/_variables.scss
- src/aurelia-slickgrid/styles/slick-bootstrap.scss
- src/aurelia-slickgrid/styles/slick-grid.scss
- add frozen to both the pre-header & header columns
- add SASS variables to customize border on these 3 properties (pre-header, header, header-row aka filter row)
> feat(styling): add frozen on all possible elements with SASS variables

- src/aurelia-slickgrid/formatters/__tests__/fakeHyperlinkFormatter.spec.ts
- src/aurelia-slickgrid/formatters/fakeHyperlinkFormatter.ts
- src/aurelia-slickgrid/formatters/index.ts
- Takes any text value and display it as a fake a hyperlink (only styled as an hyperlink)
> feat(formatters): add a fake hyperlink formatter

- src/aurelia-slickgrid/extensions/headerMenuExtension.ts
- src/aurelia-slickgrid/models/hideColumnOption.interface.ts
- src/aurelia-slickgrid/services/__tests__/grid.service.spec.ts
- src/aurelia-slickgrid/services/__tests__/gridState.service.spec.ts
- src/aurelia-slickgrid/services/__tests__/groupingAndColspan.service.spec.ts
- src/aurelia-slickgrid/services/grid.service.ts
- src/aurelia-slickgrid/services/gridState.service.ts
- src/aurelia-slickgrid/services/groupingAndColspan.service.ts
- some header group titles disappear after hiding a column
> fix(core): header columns grouping misbehave after hiding column

- src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid.spec.ts
- src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- src/aurelia-slickgrid/extensions/__tests__/rowDetailViewExtension.spec.ts
- src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts
- this also fixes RequireJS missing plugin imports with ESM Module
> fix(core): use regular imports instead of require to load plugins

- src/examples/slickgrid/example22.html
- src/examples/slickgrid/example22.scss
- src/examples/slickgrid/example22.ts
- test/cypress/integration/example03.spec.js
- test/cypress/integration/example22.spec.js
- we should resize grid after changing tab
- add more Cypress tests
> fix(examples): multiple grids in tab should show be resized

- package.json
- src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- src/examples/slickgrid/example30.ts
- test/cypress/integration/example30.spec.js
- yarn.lock
- this was mostly done in Slckgrid-Universal, just update Example and Cypress tests
>  feat(editors): add form/input reset to Composite Editor modal & fix touched value

- package.json
- src/examples/slickgrid/example34.html
- src/examples/slickgrid/example34.scss
- src/examples/slickgrid/example34.ts
- src/examples/slickgrid/index.ts
- test/cypress/integration/example01.spec.js
- test/cypress/integration/example34.spec.js
- webpack.config.js
- yarn.lock
- also make this new example the default route
> feat(demo): add new Example 34 to demo Real-time Market Trading

- .github/workflows/main.yml
- package.json
- test/cypress/package.json
- test/cypress/yarn.lock
- yarn.lock
- we don't codecov npm package since we use simple curl so let's remove it and fix a security vulnerabitlity that come from it
> chore(deps): remove codecov unnecessary pkg and update mock pkgs

- src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- src/examples/slickgrid/example19.ts
- test/cypress/e2e/example19.cy.js
- keep code in sync with Angular-Slickgrid
- add more Cypress E2E tests
> chore(plugin): pre-register Row Detail earlier

- package.json
- yarn.lock
- also remove unused dependency `duplicate-package-checker-webpack-plugin`
> chore(deps): update semver to fix security issues reported

- .eslintrc
- src/aurelia-slickgrid/custom-elements/__tests__/aurelia-slickgrid.spec.ts
- src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- src/aurelia-slickgrid/index.ts
- src/examples/slickgrid/example27.ts
- test/cypress/e2e/example23.cy.ts
- TypeScript add type-only imports and exports
> chore(build): add TypeScript type only import

- src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts
- regression fix for older version 6.x branch
- partially rolls back PR #1118 because that caused a regression that was identified by a user of Angular-Slickgrid in which defining a global external resource for ExcelExport no longer worked.
- this PR also fixes duplicatation of external resources when having multiple grid on the same page and spreading grid options of another grid (e.g.: `{ ...this.gridOptions1, sortable: false }`)
> fix: spreading 2 grids options causes duplicate ext resources

- packages/aurelia-slickgrid/src/index.ts
- packages/aurelia-slickgrid/src/models/aureliaGridInstance.interface.ts
- packages/aurelia-slickgrid/src/models/index.ts
- packages/aurelia-slickgrid/src/models/slickGrid.interface.ts
- packages/aurelia-slickgrid/src/models/viewModelBindableData.interface.ts
- packages/aurelia-slickgrid/src/models/viewModelBindableInputData.interface.ts
- packages/demo/src/examples/slickgrid/custom-aureliaViewModelEditor.ts
- packages/demo/src/examples/slickgrid/custom-aureliaViewModelFilter.ts
- packages/demo/src/examples/slickgrid/custom-inputFilter.ts
- packages/demo/src/examples/slickgrid/example12.ts
- packages/demo/src/examples/slickgrid/example20.ts
- packages/demo/src/examples/slickgrid/example23.ts
- packages/demo/src/examples/slickgrid/example24.ts
- packages/demo/src/examples/slickgrid/example3.ts
- packages/demo/src/examples/slickgrid/example30.ts
- packages/demo/src/examples/slickgrid/example32.ts
- also expect Formatter to always include SlickGrid to get GridOption
> chore: remove unnecessary SlickGrid interface

- .github/workflows/main.yml
- .vscode/tasks.json
- package.json
- packages/aurelia-slickgrid/package.json
- packages/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts
- packages/aurelia-slickgrid/src/extensions/slickRowDetailView.ts
- packages/demo/package.json
- packages/demo/src/examples/slickgrid/example34.ts
- pnpm-lock.yaml
- for development purposes we can add pnpm scripts that run in parallel so that WebPack always have the lib TS build ready and updated
> chore: run build watch & webpack dev in parallel

- packages/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts
- when loading a new grid, we are calling `grid.autosizeColumns()` to resize the columns and while adding tests for that method I incidently discovered that it was being called multiple times on a page load (up to 6-8x times) but in reality there is no need to call it more than once or twice.
- there is also no need to call the `autosizeColumns` if the grid dimension calculated by the Resizer Service are the same as the previously calculated dimensions
- the updated code will never call `autosizeColumns` more than twice on a page load, however note that the method will always be called whenever the grid dimensions or columns get updated
> perf(resizer): `autosizeColumns` is called too many times on page load

- packages/aurelia-slickgrid/package.json
- packages/aurelia-slickgrid/src/extensions/slickRowDetailView.ts
- packages/demo/package.json
- pnpm-lock.yaml
- related to issue described in Angular-Slickgrid: https://github.com/ghiscoding/Angular-Slickgrid/discussions/838#discussioncomment-8574215
> fix: switch to `isomorphic-dompurify` for SSR support

- packages/demo/src/examples/slickgrid/example24.html
- packages/demo/src/examples/slickgrid/example30.html
- packages/demo/src/examples/slickgrid/example37.html
- packages/demo/src/examples/slickgrid/example37.ts
- packages/demo/src/my-app.ts
- test/cypress/e2e/example37.cy.ts
> feat: add Footer Totals Row and fix footer styling

- packages/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts
- packages/demo/src/examples/slickgrid/example13.ts
- packages/demo/src/examples/slickgrid/example18.ts
- see this Slickgrid-Universal [comment](https://github.com/ghiscoding/slickgrid-universal/issues/1678#issuecomment-2349071503) for more details
> perf: don't invalidate grid rows more than once

- packages/aurelia-slickgrid/src/extensions/__tests__/slickRowDetailView.spec.ts
- packages/aurelia-slickgrid/src/extensions/slickRowDetailView.ts
Reverts ghiscoding/aurelia-slickgrid#1269
> Revert "fix: redraw all open row details whenever the grid is re-rendered"

- packages/demo/package.json
- packages/demo/src/examples/slickgrid/example3.ts
- packages/demo/src/examples/slickgrid/jsonp.ts
- pnpm-lock.yaml
- rewrite fetch-jsonp as ESM but only locally since this is only used for demo purposes
> chore: localize fetch-json to avoid importing old CJS package

- packages/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts
- packages/aurelia-slickgrid/src/global-grid-options.ts
- packages/demo/src/examples/slickgrid/example28.ts
> fix: add `autoResize.autoHeight` to resize by dataset length
